using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
namespace NetCrzaDevices
{
/// <summary>
///     classBMCS_10
/// </summary>
public class BMCS_10 : BMRZ
{
	public BMCS_10(int nfc, int ndev, int size_memDev, string devname)
	{
		NFC			= nfc;
		NDev			= ndev;
		DeviceName	= devname;
		varDev		= new Hashtable();
		
		varDev.Add( 60000, new Bit_FieldMT( 2, this, false ));	//  ( )
		varDev.Add( 60002, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60003, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60004, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60005, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60006, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60007, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60008, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60009, new DateTimeUTC_FieldMT( 2, this, false ));	//  ( )
		varDev.Add( 60011, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60012, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60013, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60014, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60015, new Stringz_FieldMT( 17, this, false ));	//  ( )
		varDev.Add( 60050, new UDInt_FieldMT( 2, this, false ));	//  ( )
		varDev.Add( 60052, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60053, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60054, new DateTimeUTC_FieldMT( 2, this, false ));	//  ( )
		varDev.Add( 60056, new Int_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60057, new Int_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60058, new Stringz_FieldMT( 2, this, false ));	//  ( )
		varDev.Add( 60060, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60061, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 0, new BCD_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 1, new Stringz_FieldMT( 16, this, false ));	//  ( )
		varDev.Add( 17, new BCD_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 18, new Empty_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 19, new DateTime4_FieldMT( 4, this, false ));	//  ( )
		varDev.Add( 23, new UInt_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 24, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 29, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 30, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 31, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 32, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 33, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 34, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 35, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 36, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 112, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 113, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 114, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 115, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 116, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 117, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 118, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 119, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 120, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 128, new Byte_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 129, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 130, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 131, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 132, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 184, new DateTime4_FieldMT( 4, this, false ));	//  ( )
		varDev.Add( 188, new DateTime4_FieldMT( 4, this, false ));	//  ( )
		varDev.Add( 192, new DateTime4_FieldMT( 4, this, false ));	//  ( )
		varDev.Add( 196, new DateTime4_FieldMT( 4, this, false ));	//  ( )
		varDev.Add( 200, new DateTime4_FieldMT( 4, this, false ));	//  ( )
		varDev.Add( 204, new DateTime4_FieldMT( 4, this, false ));	//  ( )
		varDev.Add( 61900, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата выгрузки из БМЦС по часам ECU)
		varDev.Add( 61902, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 1)
		varDev.Add( 61903, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 2)
		varDev.Add( 61904, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 3)
		varDev.Add( 61905, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 4)
		varDev.Add( 61906, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 5)
		varDev.Add( 61907, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 6)
		varDev.Add( 61908, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 7)
		varDev.Add( 61909, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 8)
		varDev.Add( 61910, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 9)
		varDev.Add( 61911, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 10)
		varDev.Add( 61912, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 11)
		varDev.Add( 61913, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 12)
		varDev.Add( 61914, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 13)
		varDev.Add( 61915, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 14)
		varDev.Add( 61916, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 15)
		varDev.Add( 61917, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 16 )
		varDev.Add( 61918, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 17)
		varDev.Add( 61919, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 18)
		varDev.Add( 61920, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 19)
		varDev.Add( 61921, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 20)
		varDev.Add( 61922, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 21)
		varDev.Add( 61923, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 22)
		varDev.Add( 61924, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 23)
		varDev.Add( 61925, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 24)
		varDev.Add( 61926, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 25)
		varDev.Add( 61927, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 26)
		varDev.Add( 61928, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 27)
		varDev.Add( 61929, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 28)
		varDev.Add( 61930, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 29)
		varDev.Add( 61931, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 30)
		varDev.Add( 61932, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 31)
		varDev.Add( 61933, new BCD_FieldMT( 1, this, false ));	//  (Дискретный вход 32)
		varDev.Add( 61934, new BCD_FieldMT( 1, this, false ));	//  (Вход КИС - 1)
		varDev.Add( 61935, new BCD_FieldMT( 1, this, false ));	//  (Вход КИС - 2)
		varDev.Add( 61936, new BCD_FieldMT( 1, this, false ));	//  (Вход КИС - 3)
		varDev.Add( 61937, new BCD_FieldMT( 1, this, false ));	//  (Вход квитирование)
		varDev.Add( 61938, new BCD_FieldMT( 1, this, false ));	//  (Вход квитирование ЗС)
		varDev.Add( 61941, new BCD_FieldMT( 1, this, false ));	//  (Выход ОС - 1)
		varDev.Add( 61942, new BCD_FieldMT( 1, this, false ));	//  (Выход ОС - 2)
		varDev.Add( 61943, new BCD_FieldMT( 1, this, false ));	//  (Выход ОС - 3)
		varDev.Add( 61944, new BCD_FieldMT( 1, this, false ));	//  (Выход ОС - 4)
		varDev.Add( 61945, new BCD_FieldMT( 1, this, false ));	//  (Выход ОС - 5)
		varDev.Add( 61946, new BCD_FieldMT( 1, this, false ));	//  (Выход ЗС)
		varDev.Add( 61947, new BCD_FieldMT( 1, this, false ));	//  (Выход НД)
		varDev.Add( 61948, new BCD_FieldMT( 1, this, false ));	//  (Выход НД)      
		varDev.Add( 62000, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата выгрузки из БМЦС по часам ECU)
		varDev.Add( 62002, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62003, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62004, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62005, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62006, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62007, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62008, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62009, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62010, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62011, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62012, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62013, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62014, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62015, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62016, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62017, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62018, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62019, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62020, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62021, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62022, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62023, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62024, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62025, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62026, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62027, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62028, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62029, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62030, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62031, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62032, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62033, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62034, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62035, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62036, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62037, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62038, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62039, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62040, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62041, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62042, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62043, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62044, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62045, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62046, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62047, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62048, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62049, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62050, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62051, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62052, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62053, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62054, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62055, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62056, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62057, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62058, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62059, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62060, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62061, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62062, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62063, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62064, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62065, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62066, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62067, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62068, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62069, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62070, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62071, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62072, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62073, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62074, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62075, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62076, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62077, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62078, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62079, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62080, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62081, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62082, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62083, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62084, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62085, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62086, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62087, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62088, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62089, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62090, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62091, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62092, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62093, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62094, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62095, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62096, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на трогание)
		varDev.Add( 62097, new BCDPack_FieldMT( 1, this, false ));	// 0.001с(Уставка на возврат)
		varDev.Add( 62098, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62101, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62104, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62107, new Byte_FieldMT( 1, this, false ));	//  (Тип датчика/действия на выход)
		varDev.Add( 62110, new Byte_FieldMT( 1, this, false ));	//  (Варианты управления выходными реле)
		varDev.Add( 62111, new Byte_FieldMT( 1, this, false ));	//  (Варианты управления выходными реле)
		varDev.Add( 62112, new Byte_FieldMT( 1, this, false ));	//  (Варианты управления выходными реле/Метод индикации и звуковой сигнализации)
		ConfigureMF(ref varDev, "");
	}
	public override string	ToString()
	{
		return "BMCS_10";
	}
	public override void	ConfigureMF(ref Hashtable vD, string modfileName)
	{}
}
}

