using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
namespace NetCrzaDevices
{
/// <summary>
///     classBMMRCH_A_01
/// </summary>
public class BMMRCH_A_01 : BMRZ
{
	public BMMRCH_A_01(int nfc, int ndev, int size_memDev, string devname)
	{
		NFC			= nfc;
		NDev			= ndev;
		DeviceName	= devname;
		varDev		= new Hashtable();
		
		varDev.Add( 60000, new Bit_FieldMT( 1, this, false ));	//  (Регитстр битовыхфлагов RTU)
		varDev.Add( 60001, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60002, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей аварий)
		varDev.Add( 60003, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей уставок)
		varDev.Add( 60004, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей осциллограмм)
		varDev.Add( 60005, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей максметра)
		varDev.Add( 60006, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей накопителя)
		varDev.Add( 60007, new UInt_FieldMT( 1, this, false ));	//  (Адрес на шине Modbus)
		varDev.Add( 60008, new UInt_FieldMT( 1, this, false ));	//  (Номер шины Modbus)
		varDev.Add( 60009, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата чтения по шине Modbus)
		varDev.Add( 60011, new UInt_FieldMT( 1, this, false ));	//  (Аргумент 1)
		varDev.Add( 60012, new UInt_FieldMT( 1, this, false ));	//  (Аргумент 2)
		varDev.Add( 60013, new UInt_FieldMT( 1, this, false ));	//  (Состояние протокола)
		varDev.Add( 60014, new UInt_FieldMT( 1, this, false ));	//  (Числовой идентификатор)
		varDev.Add( 60015, new Stringz_FieldMT( 17, this, false ));	//  (Текстовый идентификатор)
		varDev.Add( 60050, new UDInt_FieldMT( 2, this, false ));	//  (IP-адрес отправителя)
		varDev.Add( 60052, new UInt_FieldMT( 1, this, false ));	//  (Серия №)
		varDev.Add( 60053, new UInt_FieldMT( 1, this, false ));	//  (Пакет №)
		varDev.Add( 60054, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата поступления по часам ФК)
		varDev.Add( 60056, new Int_FieldMT( 1, this, false ));	//  (Причина отказа от выполнения)
		varDev.Add( 60057, new Int_FieldMT( 1, this, false ));	//  (Состояние выполнения команды)
		varDev.Add( 60058, new Stringz_FieldMT( 2, this, false ));	//  (Имя команды)
		varDev.Add( 60060, new UInt_FieldMT( 1, this, false ));	//  (Первый параметр команды)
		varDev.Add( 60061, new UInt_FieldMT( 1, this, false ));	//  (Второй параметр команды)
		varDev.Add( 0, new UInt_FieldMT( 1, this, false ));	//  (Версия сетевого драйвера)
		varDev.Add( 1, new Stringz_FieldMT( 16, this, false ));	//  (Идентификатор блока ASCII строка)
		varDev.Add( 17, new UInt_FieldMT( 1, this, false ));	//  (Признак достоверности слова)
		varDev.Add( 18, new UInt_FieldMT( 1, this, false ));	//  (Флаги наличия данных аварий в памяти БММРЧ)
		varDev.Add( 19, new DateTime4_FieldMT( 4, this, false ));	//  (Текущее астрономич. время)
		varDev.Add( 23, new UInt_FieldMT( 1, this, false ));	//  (Счетчик изменения состояния блока)
		varDev.Add( 24, new UInt_FieldMT( 1, this, false ));	//  (Текущее состояние блока)
		varDev.Add( 25, new UInt_FieldMT( 1, this, false ));	//  (Частота сети  - 1000 Гц)
		varDev.Add( 26, new Int_FieldMT( 1, this, false ));	//  (Скорость изменения частоты сети - 1000 Гц)
		varDev.Add( 27, new UInt_FieldMT( 1, this, false ));	//  (Напряжение сети - 10 В)
		varDev.Add( 28, new Bit_FieldMT( 1, this, false ));	//  (Состояние дискретных входов и выходов)
		varDev.Add( 29, new UInt_FieldMT( 1, this, false ));	//  (Состояние аппаратных средств)
		varDev.Add( 30, new Bit_FieldMT( 1, this, false ));	//  (Признаки неисправности блока 1)
		varDev.Add( 34, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время текущие)
		varDev.Add( 38, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время сброса накопительной информации)
		varDev.Add( 42, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время очистки журнала событий)
		varDev.Add( 46, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время начала процедуры чтения журнала событий по АСУ)
		varDev.Add( 50, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время ввода новых конфигураций и уставок)
		varDev.Add( 54, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время перехода блока в режим "Тест оператора")
		varDev.Add( 58, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время очистки памяти аварий и осциллограмм)
		varDev.Add( 62, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время сброса максметра)
		varDev.Add( 66, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент передачи по частоте -  0,001 Гц)
		varDev.Add( 68, new Real_FieldMT( 2, this, false ));	// Гц/с(Коэффициент передачи по скорости - 0,001 Гц/сек)
		varDev.Add( 70, new Real_FieldMT( 2, this, false ));	// В(Коэффициент передачи по напряжению - 0,1 В)
		varDev.Add( 89, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время фиксации максимальной частоты сети)
		varDev.Add( 88, new UInt_FieldMT( 1, this, false ));	//  (Максимальная частота сети)
		varDev.Add( 94, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время фиксации максимальной скорости изменения част. сети)
		varDev.Add( 93, new Int_FieldMT( 1, this, false ));	//  (Максимальная скорость изменения частоты сети)
		varDev.Add( 99, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время фиксации максимального напряжения сети)
		varDev.Add( 98, new UInt_FieldMT( 1, this, false ));	//  (Максимальное напряжение сети)
		varDev.Add( 104, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время фиксации минимальной частоты сети)
		varDev.Add( 103, new UInt_FieldMT( 1, this, false ));	//  (Минимальная частота сети)
		varDev.Add( 109, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время фиксации минимальной скорости изм. частоты сети)
		varDev.Add( 108, new Int_FieldMT( 1, this, false ));	//  (Минимальная скорость изменения частоты сети)
		varDev.Add( 114, new DateTime4_FieldMT( 4, this, false ));	//  (Дата и время фиксации минимального напряжения сети)
		varDev.Add( 113, new UInt_FieldMT( 1, this, false ));	//  (Минимальное напряжение сети)
		varDev.Add( 61900, new DateTimeUTC_FieldMT( 2, this, false ));	// с(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 61902, new BCD_FieldMT( 1, this, false ));	//  (Пуски реле 1)
		varDev.Add( 61903, new BCD_FieldMT( 1, this, false ));	//  (Пуски реле 2)
		varDev.Add( 61904, new BCD_FieldMT( 1, this, false ));	//  (Пуски реле 3)
		varDev.Add( 61905, new BCD_FieldMT( 1, this, false ));	//  (Пуски реле 4)
		varDev.Add( 61906, new BCD_FieldMT( 1, this, false ));	//  (Пуски реле 5)
		varDev.Add( 61907, new BCD_FieldMT( 1, this, false ));	//  (Пуски реле 6)
		varDev.Add( 61908, new BCD_FieldMT( 1, this, false ));	//  (Пуски реле 7)
		varDev.Add( 61909, new BCD_FieldMT( 1, this, false ));	//  (Пуски реле 8)
		varDev.Add( 61910, new BCD_FieldMT( 1, this, false ));	//  (Срабатывание реле 1)
		varDev.Add( 61911, new BCD_FieldMT( 1, this, false ));	//  (Срабатывание реле 2)
		varDev.Add( 61912, new BCD_FieldMT( 1, this, false ));	//  (Срабатывание реле 3)
		varDev.Add( 61913, new BCD_FieldMT( 1, this, false ));	//  (Срабатывание реле 4)
		varDev.Add( 61914, new BCD_FieldMT( 1, this, false ));	//  (Срабатывание реле 5)
		varDev.Add( 61915, new BCD_FieldMT( 1, this, false ));	//  (Срабатывание реле 6)
		varDev.Add( 61916, new BCD_FieldMT( 1, this, false ));	//  (Срабатывание реле 7)
		varDev.Add( 61917, new BCD_FieldMT( 1, this, false ));	//  (Срабатывание реле 8)
		varDev.Add( 61918, new BCD_FieldMT( 1, this, false ));	//  (Возвраты реле 1)
		varDev.Add( 61919, new BCD_FieldMT( 1, this, false ));	//  (Возвраты реле 2)
		varDev.Add( 61920, new BCD_FieldMT( 1, this, false ));	//  (Возвраты реле 3)
		varDev.Add( 61921, new BCD_FieldMT( 1, this, false ));	//  (Возвраты реле 4)
		varDev.Add( 61922, new BCD_FieldMT( 1, this, false ));	//  (Возвраты реле 5)
		varDev.Add( 61923, new BCD_FieldMT( 1, this, false ));	//  (Возвраты реле 6)
		varDev.Add( 61924, new BCD_FieldMT( 1, this, false ));	//  (Возвраты реле 7)
		varDev.Add( 61925, new BCD_FieldMT( 1, this, false ));	//  (Возвраты реле 8)
		varDev.Add( 60100, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 60102, new UInt_FieldMT( 1, this, false ));	//  (Номер аварии)
		varDev.Add( 60103, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Пуск")
		varDev.Add( 60107, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Пуск")
		varDev.Add( 60108, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Пуск")
		varDev.Add( 60109, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Пуск")
		varDev.Add( 60110, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигн)
		varDev.Add( 60111, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Срабатывание")
		varDev.Add( 60115, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Срабатывание")
		varDev.Add( 60116, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Срабатывание")
		varDev.Add( 60117, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Срабатывание")
		varDev.Add( 60118, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60119, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Возврат")
		varDev.Add( 60123, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Возврат")
		varDev.Add( 60124, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Возврат")
		varDev.Add( 60125, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Возврат")
		varDev.Add( 60126, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60128, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент по частоте, равен 0,001 Гц)
		varDev.Add( 60130, new Real_FieldMT( 2, this, false ));	//  Гц/сек(Коэффициент по скорости, равен 0,001 Гц/сек)
		varDev.Add( 60132, new Real_FieldMT( 2, this, false ));	// В(Коэффициент по напряжению, равен 0.1 В)
		varDev.Add( 60300, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 60302, new UInt_FieldMT( 1, this, false ));	//  (Номер аварии)
		varDev.Add( 60303, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Пуск")
		varDev.Add( 60307, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Пуск")
		varDev.Add( 60308, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Пуск")
		varDev.Add( 60309, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Пуск")
		varDev.Add( 60310, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60311, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Срабатывание")
		varDev.Add( 60315, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Срабатывание")
		varDev.Add( 60316, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Срабатывание")
		varDev.Add( 60317, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Срабатывание")
		varDev.Add( 60318, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60319, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Возврат")
		varDev.Add( 60323, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Возврат")
		varDev.Add( 60324, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Возврат")
		varDev.Add( 60325, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Возврат")
		varDev.Add( 60326, new Bit_FieldMT( 1, this, false ));	//  (Дискеретные сигналы)
		varDev.Add( 60328, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент по частоте, равен 0,001 Гц)
		varDev.Add( 60330, new Real_FieldMT( 2, this, false ));	//  Гц/сек(Коэффициент по скорости, равен 0,001 Гц/сек)
		varDev.Add( 60332, new Real_FieldMT( 2, this, false ));	// В(Коэффициент по напряжению, равен 0.1 В)
		varDev.Add( 60500, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 60503, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Пуск")
		varDev.Add( 60507, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Пуск")
		varDev.Add( 60508, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Пуск")
		varDev.Add( 60509, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Пуск")
		varDev.Add( 60510, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60511, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Срабатывание")
		varDev.Add( 60515, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Срабатывание")
		varDev.Add( 60516, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Срабатывание")
		varDev.Add( 60517, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Срабатывание")
		varDev.Add( 60518, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60519, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Возврат")
		varDev.Add( 60523, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Возврат")
		varDev.Add( 60524, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Возврат")
		varDev.Add( 60525, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Возврат")
		varDev.Add( 60526, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60528, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент по частоте, равен 0,001 Гц)
		varDev.Add( 60530, new Real_FieldMT( 2, this, false ));	//  Гц/сек(Коэффициент по скорости, равен 0,001 Гц/сек)
		varDev.Add( 60532, new Real_FieldMT( 2, this, false ));	// В(Коэффициент по напряжению, равен 0.1 В)
		varDev.Add( 60700, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 60702, new UInt_FieldMT( 1, this, false ));	//  (Номер аварии)
		varDev.Add( 60703, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Пуск")
		varDev.Add( 60707, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Пуск")
		varDev.Add( 60708, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Пуск")
		varDev.Add( 60709, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Пуск")
		varDev.Add( 60710, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60711, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Срабатывание")
		varDev.Add( 60715, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Срабатывание")
		varDev.Add( 60716, new UInt_FieldMT( 1, this, false ));	//  (Скорость  точки "Срабатывание")
		varDev.Add( 60717, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Срабатывание")
		varDev.Add( 60718, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60719, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Возврат")
		varDev.Add( 60723, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Возврат")
		varDev.Add( 60724, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Возврат")
		varDev.Add( 60725, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Возврат")
		varDev.Add( 60726, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60728, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент по частоте, равен 0,001 Гц)
		varDev.Add( 60730, new Real_FieldMT( 2, this, false ));	//  Гц/сек(Коэффициент по скорости, равен 0,001 Гц/сек)
		varDev.Add( 60732, new Real_FieldMT( 2, this, false ));	// В(Коэффициент по напряжению, равен 0.1 В)
		varDev.Add( 60900, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 60902, new UInt_FieldMT( 1, this, false ));	//  (Номер аварии)
		varDev.Add( 60903, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Пуск")
		varDev.Add( 60907, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Пуск")
		varDev.Add( 60908, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Пуск")
		varDev.Add( 60909, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Пуск")
		varDev.Add( 60910, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60911, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Срабатывание")
		varDev.Add( 60915, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Срабатывание")
		varDev.Add( 60916, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Срабатывание")
		varDev.Add( 60917, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Срабатывание")
		varDev.Add( 60918, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60919, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Возврат")
		varDev.Add( 60923, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Возврат")
		varDev.Add( 60924, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Возврат")
		varDev.Add( 60925, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Возврат")
		varDev.Add( 60926, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 60928, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент по частоте, равен 0,001 Гц)
		varDev.Add( 60930, new Real_FieldMT( 2, this, false ));	//  Гц/сек(Коэффициент по скорости, равен 0,001 Гц/сек)
		varDev.Add( 60932, new Real_FieldMT( 2, this, false ));	// В(Коэффициент по напряжению, равен 0.1 В)
		varDev.Add( 61100, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 61102, new UInt_FieldMT( 1, this, false ));	//  (Номер аварии)
		varDev.Add( 61103, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Пуск")
		varDev.Add( 61107, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Пуск")
		varDev.Add( 61108, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Пуск")
		varDev.Add( 61109, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Пуск")
		varDev.Add( 61110, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61111, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Срабатывание")
		varDev.Add( 61115, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Срабатывание")
		varDev.Add( 61116, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Срабатывание")
		varDev.Add( 61117, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Срабатывание")
		varDev.Add( 61118, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61119, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Возврат")
		varDev.Add( 61123, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Возврат")
		varDev.Add( 61124, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Возврат")
		varDev.Add( 61125, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Возврат")
		varDev.Add( 61126, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61128, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент по частоте, равен 0,001 Гц)
		varDev.Add( 61130, new Real_FieldMT( 2, this, false ));	//  Гц/сек(Коэффициент по скорости, равен 0,001 Гц/сек)
		varDev.Add( 61132, new Real_FieldMT( 2, this, false ));	// В(Коэффициент по напряжению, равен 0.1 В)
		varDev.Add( 61300, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 61302, new UInt_FieldMT( 1, this, false ));	//  (Номер аварии)
		varDev.Add( 61303, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Пуск")
		varDev.Add( 61307, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Пуск")
		varDev.Add( 61308, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Пуск")
		varDev.Add( 61309, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Пуск")
		varDev.Add( 61310, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61311, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Срабатывание")
		varDev.Add( 61315, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Срабатывание")
		varDev.Add( 61316, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Срабатывание")
		varDev.Add( 61317, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Срабатывание")
		varDev.Add( 61318, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61319, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Возврат")
		varDev.Add( 61323, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Возврат")
		varDev.Add( 61324, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Возврат")
		varDev.Add( 61325, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Возврат")
		varDev.Add( 61326, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61328, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент по частоте, равен 0,001 Гц)
		varDev.Add( 61330, new Real_FieldMT( 2, this, false ));	//  Гц/сек(Коэффициент по скорости, равен 0,001 Гц/сек)
		varDev.Add( 61332, new Real_FieldMT( 2, this, false ));	// В(Коэффициент по напряжению, равен 0.1 В)
		varDev.Add( 61500, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 61502, new UInt_FieldMT( 1, this, false ));	//  (Номер аварии)
		varDev.Add( 61503, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Пуск")
		varDev.Add( 61507, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Пуск")
		varDev.Add( 61508, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Пуск")
		varDev.Add( 61509, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Пуск")
		varDev.Add( 61510, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61511, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Срабатывание")
		varDev.Add( 61515, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Срабатывание")
		varDev.Add( 61516, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Срабатывание")
		varDev.Add( 61517, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Срабатывание")
		varDev.Add( 61518, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61519, new DateTime4_FieldMT( 4, this, false ));	//  (Астрономическое время регистрации точки "Возврат")
		varDev.Add( 61523, new UInt_FieldMT( 1, this, false ));	//  (Частота  точки "Возврат")
		varDev.Add( 61524, new Int_FieldMT( 1, this, false ));	//  (Скорость  точки "Возврат")
		varDev.Add( 61525, new UInt_FieldMT( 1, this, false ));	//  (Напряжение точки "Возврат")
		varDev.Add( 61526, new Bit_FieldMT( 1, this, false ));	//  (Дискретные сигналы)
		varDev.Add( 61528, new Real_FieldMT( 2, this, false ));	// Гц(Коэффициент по частоте, равен 0,001 Гц)
		varDev.Add( 61530, new Real_FieldMT( 2, this, false ));	//  Гц/сек(Коэффициент по скорости, равен 0,001 Гц/сек)
		varDev.Add( 61532, new Real_FieldMT( 2, this, false ));	// В(Коэффициент по напряжению, равен 0.1 В)
		varDev.Add( 62000, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 62002, new UInt_FieldMT( 1, this, false ));	//  (Номер АПМ)
		varDev.Add( 62003, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62004, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62005, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62006, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62007, new Bit_FieldMT( 1, this, false ));	//  (Программный ключ)
		varDev.Add( 62008, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62009, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62010, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62011, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62012, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62013, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62014, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62015, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62016, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62017, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62018, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62019, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62020, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62021, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62022, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62023, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62024, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62025, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62026, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62027, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 62028, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62029, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62030, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62031, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62032, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62033, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62034, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62035, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62036, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62037, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62038, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62039, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62040, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62041, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62042, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62043, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62044, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62045, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62046, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62047, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 62049, new UInt_FieldMT( 1, this, false ));	//  (Номер АПМ)
		varDev.Add( 62050, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62051, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62052, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62053, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62054, new Bit_FieldMT( 1, this, false ));	//  (программные ключи)
		varDev.Add( 62055, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62056, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62057, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62058, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62059, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62060, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62061, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62062, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62063, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62064, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62065, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62066, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62067, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62068, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62069, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62070, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62071, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62072, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62073, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62074, new Bit_FieldMT( 1, this, false ));	//  (программные ключи)
		varDev.Add( 62075, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62076, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62077, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62078, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62079, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62080, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62081, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62082, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62083, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62084, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62085, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62086, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62087, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62088, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62089, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62090, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62091, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62092, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62093, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62094, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 62096, new UInt_FieldMT( 1, this, false ));	//  (Номер АПМ)
		varDev.Add( 62097, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62098, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62099, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62100, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62101, new Bit_FieldMT( 1, this, false ));	//  (Программный ключ)
		varDev.Add( 62102, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62103, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62104, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62105, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62106, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62107, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62108, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62109, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62110, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62111, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62112, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62113, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62114, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62115, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62116, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62117, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62118, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62119, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62120, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62121, new Bit_FieldMT( 1, this, false ));	//  (Программный ключ)
		varDev.Add( 62122, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62123, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62124, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62125, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62126, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62127, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62128, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62129, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62130, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62131, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62132, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62133, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62134, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62135, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62136, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62137, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62138, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62139, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62140, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62141, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 62143, new UInt_FieldMT( 1, this, false ));	//  (Номер АПМ)
		varDev.Add( 62144, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62145, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62146, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62147, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62148, new Bit_FieldMT( 1, this, false ));	//  (программный ключ)
		varDev.Add( 62149, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62150, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62151, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62152, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62153, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62154, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62155, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62156, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62157, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62158, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62159, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62160, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62161, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62162, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62163, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62164, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62165, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62166, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62167, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62168, new Bit_FieldMT( 1, this, false ));	//  (программный ключ)
		varDev.Add( 62169, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62170, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62171, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62172, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62173, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62174, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62175, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62176, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62177, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62178, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62179, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62180, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62181, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62182, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62183, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62184, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62185, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62186, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62187, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62188, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 62190, new UInt_FieldMT( 1, this, false ));	//  (Номер АПМ)
		varDev.Add( 62191, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62192, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62193, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62194, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62195, new Bit_FieldMT( 1, this, false ));	//  (программный ключ)
		varDev.Add( 62196, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62197, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62198, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62199, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62200, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62201, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62202, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62203, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62204, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62205, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62206, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62207, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62208, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62209, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62210, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62211, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62212, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62213, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62214, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62215, new Bit_FieldMT( 1, this, false ));	//  (программный ключ)
		varDev.Add( 62216, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62217, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62218, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62219, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62220, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62221, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62222, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62223, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62224, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62225, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62226, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62227, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62228, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62229, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62230, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62231, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62232, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62233, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62234, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62235, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 62237, new UInt_FieldMT( 1, this, false ));	//  (Номер АПМ)
		varDev.Add( 62238, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62239, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62240, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62241, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62242, new Bit_FieldMT( 1, this, false ));	//  (программный ключ)
		varDev.Add( 62243, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62244, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62245, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62246, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62247, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62248, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62249, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62250, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62251, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62252, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62253, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62254, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62255, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62256, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62257, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62258, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62259, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62260, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62261, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62262, new Bit_FieldMT( 1, this, false ));	//  (программный ключ)
		varDev.Add( 62263, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62264, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62265, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62266, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62267, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62268, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62269, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62270, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62271, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62272, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62273, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62274, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62275, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62276, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62277, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62278, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62279, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62280, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62281, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62282, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 62284, new UInt_FieldMT( 1, this, false ));	//  (Номер АПМ)
		varDev.Add( 62285, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62286, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62287, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62288, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62289, new Bit_FieldMT( 1, this, false ));	//  (программный ключ)
		varDev.Add( 62290, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62291, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62292, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62293, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62294, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62295, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62296, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62297, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62298, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62299, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62300, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62301, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62302, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62303, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62304, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62305, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62306, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62307, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62308, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62309, new Bit_FieldMT( 1, this, false ));	//  (программный ключ)
		varDev.Add( 62310, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62311, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62312, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62313, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62314, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62315, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62316, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62317, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62318, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62319, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62320, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62321, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62322, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62323, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62324, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62325, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62326, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62327, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62328, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62329, new DateTimeUTC_FieldMT( 2, this, false ));	// c(Дата выгрузки из БММРЧ по часам ECU)
		varDev.Add( 62331, new UInt_FieldMT( 1, this, false ));	//  (Номер АПМ)
		varDev.Add( 62332, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62333, new Byte_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62334, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62335, new BCDPack_FieldMT( 1, this, false ));	//  (Конфигурация АПМ)
		varDev.Add( 62336, new Bit_FieldMT( 1, this, false ));	//  (программный ключи)
		varDev.Add( 62337, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62338, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62339, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62340, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62341, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62342, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62343, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62344, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62345, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62346, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62347, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62348, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62349, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62350, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62351, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62352, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62353, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62354, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62355, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 62356, new Bit_FieldMT( 1, this, false ));	//  (программный ключи)
		varDev.Add( 62357, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота срабатывания АЧР1)
		varDev.Add( 62358, new BCDPack_FieldMT( 1, this, false ));	// от 6 до 99, BCDPack* Тпп (полупериодов сети)(Задержка срабатывания АЧР1)
		varDev.Add( 62359, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Блокировка АЧР1 по скорости)
		varDev.Add( 62360, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота пуска АЧР2)
		varDev.Add( 62361, new BCDPack_FieldMT( 1, this, false ));	// от 45.0 до 50.0 Гц, BCDPack*0.1Гц(Частота возврата АЧР2)
		varDev.Add( 62362, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2)
		varDev.Add( 62363, new BCDPack_FieldMT( 1, this, false ));	// от 0.50 до 0.70 Uном, BCDPack*0.01 Uном(Напряжение пуска АЧР2-Н)
		varDev.Add( 62364, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени АЧР2-Н)
		varDev.Add( 62365, new BCDPack_FieldMT( 1, this, false ));	// от -0.0 до -20 Гц/с, BCDPack*0.1 Гц/с(Скорость срабатывания АЧРС)
		varDev.Add( 62366, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота разрешения АЧРС)
		varDev.Add( 62367, new BCDPack_FieldMT( 1, this, false ));	// от 49.0 до 50.0 Гц, BCDPack*0.1 Гц(Частота пуска ЧАПВ )
		varDev.Add( 62368, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDРack*0.01с (Выдержка времени ЧАПВ)
		varDev.Add( 62369, new BCDPack_FieldMT( 1, this, false ));	// от 0.70 до 1.00 Uном, BCDPack*0.01 Uном(Напряжение пуска ЧАПВ)
		varDev.Add( 62370, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Частота пуска АОПЧ)
		varDev.Add( 62371, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Выдержка пуска АОПЧ)
		varDev.Add( 62372, new BCDPack_FieldMT( 1, this, false ));	// от 0.1 до 20.0 Гц/с, BCDPack*0.01 c(Ускорение АОПЧ по скорости)
		varDev.Add( 62373, new BCDPack_FieldMT( 1, this, false ));	// от 0 до 99.99 с, BCDPack*0.01 c(Частота снятия АОПЧ)
		varDev.Add( 62374, new BCDPack_FieldMT( 1, this, false ));	// от 50 до 53.0 Гц, BCDPack*0.1 Гц(Выдержка снятия АОПЧ)
		varDev.Add( 62375, new BCDPack_FieldMT( 1, this, false ));	// от -0.1 до -20 Гц/с, BCDPack*0.1 Гц/с(Ускорение снятия АРПЧ по скорости)
		varDev.Add( 72, new Bit_FieldMT( 1, this, false ));	// (Признаки свечения СД)
		varDev.Add( 73, new Bit_FieldMT( 1, this, false ));	// (Признаки мигания СД)
		varDev.Add( 74, new Bit_FieldMT( 1, this, false ));	// (Признаки неисправностей реле)
		ConfigureMF(ref varDev, "");
	}
	public override string	ToString()
	{
		return "BMMRCH_A_01";
	}
	public override void	ConfigureMF(ref Hashtable vD, string modfileName)
	{}
}
}

