using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
namespace NetCrzaDevices
{
/// <summary>
///     classBMRZ_KL_09_33_12
/// </summary>
public class BMRZ_KL_09_33_12 : BMRZ
{
	public BMRZ_KL_09_33_12(int nfc, int ndev, int size_memDev, string devname)
	{
		NFC			= nfc;
		NDev			= ndev;
		DeviceName	= devname;
		varDev		= new Hashtable();
		
		varDev.Add( 60000, new Bit_FieldMT( 1, this, false ));	//  (Регистр битовых флагов RTU)
		varDev.Add( 60001, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60002, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей аварий)
		varDev.Add( 60003, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей уставок)
		varDev.Add( 60004, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей осциллограмм)
		varDev.Add( 60005, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей максметра)
		varDev.Add( 60006, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей накопителя)
		varDev.Add( 60007, new UInt_FieldMT( 1, this, false ));	//  (Адрес на шине Modbus)
		varDev.Add( 60008, new UInt_FieldMT( 1, this, false ));	//  (Номер шины Modbus)
		varDev.Add( 60009, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата чтения по шине Modbus)
		varDev.Add( 60011, new UInt_FieldMT( 1, this, false ));	//  (Аргумент 1)
		varDev.Add( 60012, new UInt_FieldMT( 1, this, false ));	//  (Аргумент 2)
		varDev.Add( 60013, new UInt_FieldMT( 1, this, false ));	//  (Состояние протокола)
		varDev.Add( 60014, new UInt_FieldMT( 1, this, false ));	//  (Числовой идентификатор)
		varDev.Add( 60015, new Stringz_FieldMT( 17, this, false ));	//  (Текстовый идентификатор)
		varDev.Add( 0, new BCD_FieldMT( 1, this, false ));	//  (Номер конфигурации)
		varDev.Add( 1, new Stringz_FieldMT( 16, this, false ));	//  (Идентификатор)
		varDev.Add( 17, new BCD_FieldMT( 2, this, false ));	//  (Версия сетевого драйвера)
		varDev.Add( 19, new DateTime4_FieldMT( 4, this, false ));	//  (Текущее астрономич. время)
		varDev.Add( 23, new UInt_FieldMT( 1, this, false ));	//  (Счетчик изменения накопительной информации)
		varDev.Add( 60050, new UDInt_FieldMT( 2, this, false ));	//  (IP-адрес отправителя)
		varDev.Add( 60052, new UInt_FieldMT( 1, this, false ));	//  (Серия №)
		varDev.Add( 60053, new UInt_FieldMT( 1, this, false ));	//  (Пакет №)
		varDev.Add( 60054, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата поступления по часам ФК)
		varDev.Add( 60056, new Int_FieldMT( 1, this, false ));	//  (Причина отказа от выполнения)
		varDev.Add( 60057, new Int_FieldMT( 1, this, false ));	//  (Состояние выполнения команды)
		varDev.Add( 60058, new Stringz_FieldMT( 2, this, false ));	//  (Имя команды)
		varDev.Add( 60060, new UInt_FieldMT( 1, this, false ));	//  (Первый параметр команды)
		varDev.Add( 60061, new UInt_FieldMT( 1, this, false ));	//  (Второй параметр команды)
		varDev.Add( 24, new Bit_FieldMT( 1, this, false ));	//  (Слово статуса)
		varDev.Add( 25, new Bit_FieldMT( 1, this, false ));	//  (Входные дискретные сигналы)
		varDev.Add( 26, new Bit_FieldMT( 1, this, false ));	//  (Входные/выходные  дискретные сигналы)
		varDev.Add( 27, new Bit_FieldMT( 1, this, false ));	//  (Выходные  дискретные сигналы)
		varDev.Add( 28, new Bit_FieldMT( 1, this, false ));	//  (Cлово состояния сигнала Вызов)
		varDev.Add( 30, new Bit_FieldMT( 1, this, false ));	//  (Слово состояния неисправности БМРЗ)
		varDev.Add( 32, new Bit_FieldMT( 1, this, false ));	//  (Слово состояния неисправности БМРЗ)
		varDev.Add( 33, new Int_FieldMT( 1, this, false ));	// А(Ia=)
		varDev.Add( 34, new Int_FieldMT( 1, this, false ));	// А(Ib=)
		varDev.Add( 35, new Int_FieldMT( 1, this, false ));	// А(Ic=)
		varDev.Add( 36, new Int_FieldMT( 1, this, false ));	// А(3Io=)
		varDev.Add( 37, new Int_FieldMT( 1, this, false ));	// В(3Uo=)
		varDev.Add( 38, new Int_FieldMT( 1, this, false ));	// В(Uab=)
		varDev.Add( 39, new Int_FieldMT( 1, this, false ));	// В(Ubc=)
		varDev.Add( 41, new Int_FieldMT( 1, this, false ));	// В(U2=)
		varDev.Add( 42, new Int_FieldMT( 1, this, false ));	// А(I2=)
		varDev.Add( 43, new Int_FieldMT( 1, this, false ));	// А(3Ioвг=)
		varDev.Add( 45, new Int_FieldMT( 1, this, false ));	// Гр(Фa^bc=)
		varDev.Add( 47, new Int_FieldMT( 1, this, false ));	// Гр(Фс^ab=)
		varDev.Add( 50, new Int_FieldMT( 1, this, false ));	// Гц(F=)
		varDev.Add( 51, new Bit_FieldMT( 1, this, false ));	//  (Признаки направления мощности, достоверности)
		varDev.Add( 139, new Int_FieldMT( 1, this, false ));	//  (Ia)
		varDev.Add( 140, new Int_FieldMT( 1, this, false ));	//  (Ib)
		varDev.Add( 141, new Int_FieldMT( 1, this, false ));	//  (Ic)
		varDev.Add( 142, new Int_FieldMT( 1, this, false ));	//  (3I0)
		varDev.Add( 143, new Int_FieldMT( 1, this, false ));	//  (3U0)
		varDev.Add( 144, new Int_FieldMT( 1, this, false ));	// c(Максимальное время срабатывания выключателя)
		varDev.Add( 145, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации Ia)
		varDev.Add( 149, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации Ib)
		varDev.Add( 153, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации Ic)
		varDev.Add( 157, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации 3I0)
		varDev.Add( 161, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации 3U0)
		varDev.Add( 169, new DateTime4_FieldMT( 4, this, false ));	//  (астрономическое время регистрации max/min значений   )
		varDev.Add( 195, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 197, new Real_FieldMT( 2, this, false ));	// А(Ib=)
		varDev.Add( 199, new Real_FieldMT( 2, this, false ));	// А(Ic=)
		varDev.Add( 201, new Real_FieldMT( 2, this, false ));	// А(3Io=)
		varDev.Add( 203, new Real_FieldMT( 2, this, false ));	// В(3Uo=)
		varDev.Add( 205, new Real_FieldMT( 2, this, false ));	// В(Uab=)
		varDev.Add( 207, new Real_FieldMT( 2, this, false ));	// В(Ubc=)
		varDev.Add( 211, new Real_FieldMT( 2, this, false ));	// В(U2=)
		varDev.Add( 213, new Real_FieldMT( 2, this, false ));	// А(I2=)
		varDev.Add( 215, new Real_FieldMT( 2, this, false ));	// А(3Ioвг=)
		varDev.Add( 219, new Real_FieldMT( 2, this, false ));	// Гр(Фa^bc=)
		varDev.Add( 223, new Real_FieldMT( 2, this, false ));	// Гр(Фс^ab=)
		varDev.Add( 229, new Real_FieldMT( 2, this, false ));	// Гц(F=)
		varDev.Add( 10280, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата приема по часам ФК)
		varDev.Add( 10282, new Bit_FieldMT( 1, this, false ));	//  (Коды срабатывания защиты)
		varDev.Add( 10283, new Bit_FieldMT( 1, this, false ));	//  (Фазы максимального тока,признак срабатывания по ускорению)
		varDev.Add( 10284, new Bit_FieldMT( 1, this, false ));	//  (Коды пускавшихся защит)
		varDev.Add( 10285, new Int_FieldMT( 1, this, false ));	// А(Ia=)
		varDev.Add( 10286, new Int_FieldMT( 1, this, false ));	// А(Ib=)
		varDev.Add( 10287, new Int_FieldMT( 1, this, false ));	// А(Ic=)
		varDev.Add( 10288, new Int_FieldMT( 1, this, false ));	// А(3Io=)
		varDev.Add( 10289, new Int_FieldMT( 1, this, false ));	// В(3Uo=)
		varDev.Add( 10290, new Int_FieldMT( 1, this, false ));	// В(Uab=)
		varDev.Add( 10291, new Int_FieldMT( 1, this, false ));	// В(Ubc=)
		varDev.Add( 10293, new Int_FieldMT( 1, this, false ));	// В(U2=)
		varDev.Add( 10294, new Int_FieldMT( 1, this, false ));	// А(I2=)
		varDev.Add( 10295, new Int_FieldMT( 1, this, false ));	// А(3Ioвг=)
		varDev.Add( 10297, new Int_FieldMT( 1, this, false ));	// Гр(Фa^bc=)
		varDev.Add( 10299, new Int_FieldMT( 1, this, false ));	// Гр(Фс^ab=)
		varDev.Add( 10302, new Int_FieldMT( 1, this, false ));	// Гц(F=)
		varDev.Add( 10303, new Bit_FieldMT( 1, this, false ));	//  (Hаправления мощностей на момент пуска защит)
		varDev.Add( 10304, new Int_FieldMT( 1, this, false ));	// А(Ia=)
		varDev.Add( 10305, new Int_FieldMT( 1, this, false ));	// А(Ib=)
		varDev.Add( 10306, new Int_FieldMT( 1, this, false ));	// А(Ic=)
		varDev.Add( 10307, new Int_FieldMT( 1, this, false ));	// А(3Io=)
		varDev.Add( 10308, new Int_FieldMT( 1, this, false ));	// В(3Uo=)
		varDev.Add( 10309, new Int_FieldMT( 1, this, false ));	// В(Uab=)
		varDev.Add( 10310, new Int_FieldMT( 1, this, false ));	// В(Ubc=)
		varDev.Add( 10312, new Int_FieldMT( 1, this, false ));	// В(U2=)
		varDev.Add( 10313, new Int_FieldMT( 1, this, false ));	// А(I2=)
		varDev.Add( 10314, new Int_FieldMT( 1, this, false ));	// А(3Ioвг=)
		varDev.Add( 10316, new Int_FieldMT( 1, this, false ));	// Гр(Фa^bc=)
		varDev.Add( 10318, new Int_FieldMT( 1, this, false ));	// Гр(Фс^ab=)
		varDev.Add( 10321, new Int_FieldMT( 1, this, false ));	// Гц(F=)
		varDev.Add( 10322, new Bit_FieldMT( 1, this, false ));	//  (Hаправления мощностей на момент срабатывания защит)
		varDev.Add( 10323, new UInt_FieldMT( 1, this, false ));	// 1/100c(Выдержка)
		varDev.Add( 10324, new UInt_FieldMT( 1, this, false ));	// 1/100c(Время срабатывания выключателя)
		varDev.Add( 10325, new Bit_FieldMT( 1, this, false ));	//  (Входные дискретные сигналы на момент пуска защит)
		varDev.Add( 10326, new Bit_FieldMT( 1, this, false ));	//  (Входные/выходные дискретные сигналы на момент пуска защит)
		varDev.Add( 10327, new Bit_FieldMT( 1, this, false ));	//  (Выходные дискретные сигналы на момент пуска защит)
		varDev.Add( 10328, new Bit_FieldMT( 1, this, false ));	//  (Изм. входных дискр. сигналов с момента пуска защит до момента их срабатывания)
		varDev.Add( 10329, new Bit_FieldMT( 1, this, false ));	//  (Изм. входных/выходных дискр. сигналов с момента пуска защит до момента их срабатывания)
		varDev.Add( 10330, new Bit_FieldMT( 1, this, false ));	//  (Изм. выходных дискр. сигналов с момента пуска защит до момента их срабатывания)
		varDev.Add( 10376, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 10378, new Real_FieldMT( 2, this, false ));	// А(Ib=)
		varDev.Add( 10380, new Real_FieldMT( 2, this, false ));	// А(Ic=)
		varDev.Add( 10382, new Real_FieldMT( 2, this, false ));	// А(3Io=)
		varDev.Add( 10384, new Real_FieldMT( 2, this, false ));	// В(3Uo=)
		varDev.Add( 10386, new Real_FieldMT( 2, this, false ));	// В(Uab=)
		varDev.Add( 10388, new Real_FieldMT( 2, this, false ));	// В(Ubc=)
		varDev.Add( 10392, new Real_FieldMT( 2, this, false ));	// В(U2=)
		varDev.Add( 10394, new Real_FieldMT( 2, this, false ));	// А(I2=)
		varDev.Add( 10396, new Real_FieldMT( 2, this, false ));	// А(3Ioвг=)
		varDev.Add( 10400, new Real_FieldMT( 2, this, false ));	// Гр(Фa^bc=)
		varDev.Add( 10404, new Real_FieldMT( 2, this, false ));	// Гр(Фс^ab=)
		varDev.Add( 10410, new Real_FieldMT( 2, this, false ));	// Гц(F=)
		varDev.Add( 62000, new DateTimeUTC_FieldMT( 2, this, false ));	//  (дата приема по часам ФК)
		varDev.Add( 62002, new DateTime4_FieldMT( 4, this, false ));	//  (астрономическое время записи уставок)
		varDev.Add( 62006, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ Tу=)
		varDev.Add( 62007, new BCDPack_FieldMT( 1, this, false ));	// А(ЗОФ I2=)
		varDev.Add( 62008, new BCDPack_FieldMT( 1, this, false ));	// с(ЗОФ Tзоф=)
		varDev.Add( 62009, new BCDPack_FieldMT( 1, this, false ));	// В(ЗМН U=)
		varDev.Add( 62010, new BCDPack_FieldMT( 1, this, false ));	// В(ЗМН U2=)
		varDev.Add( 62011, new BCDPack_FieldMT( 1, this, false ));	// с(ЗМН Тзмн=)
		varDev.Add( 62012, new BCDPack_FieldMT( 1, this, false ));	// с(ЧАПВ Тчапв=)
		varDev.Add( 62013, new BCDPack_FieldMT( 1, this, false ));	// с(АЧР Тачр=)
		varDev.Add( 62014, new BCDPack_FieldMT( 1, this, false ));	// с(Tуров=)
		varDev.Add( 62015, new BCDPack_FieldMT( 1, this, false ));	// с(АПВ Тапв1=)
		varDev.Add( 62016, new BCDPack_FieldMT( 1, this, false ));	// с(АПВ Тапв2=)
		varDev.Add( 62017, new BCDPack_FieldMT( 1, this, false ));	// Гц(ЗПП Fзпп<1=)
		varDev.Add( 62018, new BCDPack_FieldMT( 1, this, false ));	// Гц(ЗПП Fзпп<2=)
		varDev.Add( 62019, new BCDPack_FieldMT( 1, this, false ));	// с(ЗПП Тзпп=)
		varDev.Add( 62020, new BCDPack_FieldMT( 1, this, false ));	// В(ЗПН U=)
		varDev.Add( 62021, new BCDPack_FieldMT( 1, this, false ));	// В(ЗПН U2=)
		varDev.Add( 62022, new BCDPack_FieldMT( 1, this, false ));	// с(ЗПН Тзпн=)
		varDev.Add( 62023, new BCDPack_FieldMT( 1, this, false ));	// В(ЗСН U=)
		varDev.Add( 62024, new BCDPack_FieldMT( 1, this, false ));	// В(ЗСН U2=)
		varDev.Add( 62025, new BCDPack_FieldMT( 1, this, false ));	// с(ЗСН Тзсн=)
		varDev.Add( 62026, new BCDPack_FieldMT( 1, this, false ));	// с(ТН Тн=)
		varDev.Add( 62027, new BCDPack_FieldMT( 1, this, false ));	// гр(ДН Фф=)
		varDev.Add( 62028, new BCDPack_FieldMT( 1, this, false ));	// гр(ДН Фо=)
		varDev.Add( 62029, new BCDPack_FieldMT( 1, this, false ));	// A(Iуров=)
		varDev.Add( 62030, new UInt_FieldMT( 1, this, false ));	//  (Вход 1)
		varDev.Add( 62031, new UInt_FieldMT( 1, this, false ));	//  (Вход 2)
		varDev.Add( 62032, new UInt_FieldMT( 1, this, false ));	//  (Вход 3)
		varDev.Add( 62033, new UInt_FieldMT( 1, this, false ));	//  (Вход 4)
		varDev.Add( 62034, new UInt_FieldMT( 1, this, false ));	//  (Вход 5)
		varDev.Add( 62035, new UInt_FieldMT( 1, this, false ));	//  (Вход 6)
		varDev.Add( 62036, new UInt_FieldMT( 1, this, false ));	//  (Выход 1)
		varDev.Add( 62037, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 1 Ти=)
		varDev.Add( 62038, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 1 Тз=)
		varDev.Add( 62039, new UInt_FieldMT( 1, this, false ));	//  (Выход 2)
		varDev.Add( 62040, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 2 Ти=)
		varDev.Add( 62041, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 2 Тз=)
		varDev.Add( 62042, new UInt_FieldMT( 1, this, false ));	//  (Выход 3)
		varDev.Add( 62043, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 3 Ти=)
		varDev.Add( 62044, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 3 Тз=)
		varDev.Add( 62045, new UInt_FieldMT( 1, this, false ));	//  (Выход 4)
		varDev.Add( 62046, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 4 Ти=)
		varDev.Add( 62047, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 4 Тз=)
		varDev.Add( 62048, new UInt_FieldMT( 1, this, false ));	//  (Выход 5)
		varDev.Add( 62049, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 5 Ти=)
		varDev.Add( 62050, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 5 Тз=)
		varDev.Add( 62051, new UInt_FieldMT( 1, this, false ));	//  (Выход 6)
		varDev.Add( 62052, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 6 Ти=)
		varDev.Add( 62053, new BCDPack_FieldMT( 1, this, false ));	// с(Выход 6 Тз=)
		varDev.Add( 62054, new BCDPack_FieldMT( 1, this, false ));	// А(МТЗ I>>>=)
		varDev.Add( 62055, new BCDPack_FieldMT( 1, this, false ));	// А(МТЗ I>>=)
		varDev.Add( 62056, new BCDPack_FieldMT( 1, this, false ));	// А(МТЗ Iн>=)
		varDev.Add( 62057, new BCDPack_FieldMT( 1, this, false ));	// А(МТЗ Iз>=)
		varDev.Add( 62058, new BCDPack_FieldMT( 1, this, false ));	// В(МТЗ U=)
		varDev.Add( 62059, new BCDPack_FieldMT( 1, this, false ));	// В(МТЗ U2=)
		varDev.Add( 62060, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ T>>>=)
		varDev.Add( 62061, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ T>>=)
		varDev.Add( 62062, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ Tн>=)
		varDev.Add( 62063, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ Tз>=)
		varDev.Add( 62064, new BCDPack_FieldMT( 1, this, false ));	// В(ОЗЗ 3Uo=)
		varDev.Add( 62065, new BCDPack_FieldMT( 1, this, false ));	// А(ОЗЗ 3Io=)
		varDev.Add( 62066, new BCDPack_FieldMT( 1, this, false ));	// с(ОЗЗ Tозз1=)
		varDev.Add( 62067, new BCDPack_FieldMT( 1, this, false ));	// с(ОЗЗ Tозз2=)
		varDev.Add( 62068, new BCDPack_FieldMT( 1, this, false ));	// А(МТЗ I>>>=)
		varDev.Add( 62069, new BCDPack_FieldMT( 1, this, false ));	// А(МТЗ I>>=)
		varDev.Add( 62070, new BCDPack_FieldMT( 1, this, false ));	// А(МТЗ Iн>=)
		varDev.Add( 62071, new BCDPack_FieldMT( 1, this, false ));	// А(МТЗ Iз>=)
		varDev.Add( 62072, new BCDPack_FieldMT( 1, this, false ));	// В(МТЗ U=)
		varDev.Add( 62073, new BCDPack_FieldMT( 1, this, false ));	// В(МТЗ U2=)
		varDev.Add( 62074, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ T>>>=)
		varDev.Add( 62075, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ T>>=)
		varDev.Add( 62076, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ Tн>=)
		varDev.Add( 62077, new BCDPack_FieldMT( 1, this, false ));	// с(МТЗ Tз>=)
		varDev.Add( 62078, new BCDPack_FieldMT( 1, this, false ));	// В(ОЗЗ 3Uo=)
		varDev.Add( 62079, new BCDPack_FieldMT( 1, this, false ));	// А(ОЗЗ 3Io=)
		varDev.Add( 62080, new BCDPack_FieldMT( 1, this, false ));	// с(ОЗЗ Tозз1=)
		varDev.Add( 62081, new BCDPack_FieldMT( 1, this, false ));	// с(ОЗЗ Tозз2=)
		varDev.Add( 62082, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62084, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62085, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62086, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62087, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62090, new BCD_FieldMT( 1, this, false ));	//  (Числитель коэффищиента трансформации для фазных токов Ia, Ib, Ic)
		varDev.Add( 62091, new BCD_FieldMT( 1, this, false ));	//  (Знаменатель коэффищиента трансформации для фазных токов Ia, Ib, Ic)
		varDev.Add( 62092, new BCD_FieldMT( 1, this, false ));	//  (Коэффициент трансформации тока 3Io)
		varDev.Add( 62100, new DateTimeUTC_FieldMT( 2, this, false ));	//  (дата приема по часам ФК )
		varDev.Add( 62102, new Real_FieldMT( 2, this, false ));	// A(Ia)
		varDev.Add( 62104, new Real_FieldMT( 2, this, false ));	// A(Ib)
		varDev.Add( 62106, new Real_FieldMT( 2, this, false ));	// A(Ic)
		varDev.Add( 62108, new Int_FieldMT( 1, this, false ));	// A(Ia)
		varDev.Add( 62109, new Int_FieldMT( 1, this, false ));	// A(Ib)
		varDev.Add( 62110, new Int_FieldMT( 1, this, false ));	// A(Ic)
		varDev.Add( 62111, new BCD_FieldMT( 1, this, false ));	//  (Суммарное количество отключений)
		varDev.Add( 62112, new BCD_FieldMT( 1, this, false ));	//  (МТЗ I>>>пуск)
		varDev.Add( 62113, new BCD_FieldMT( 1, this, false ));	//  (МТЗ I>>>откл)
		varDev.Add( 62114, new BCD_FieldMT( 1, this, false ));	//  (МТЗ I>>пуск)
		varDev.Add( 62115, new BCD_FieldMT( 1, this, false ));	//  (МТЗ I>>откл)
		varDev.Add( 62116, new BCD_FieldMT( 1, this, false ));	//  (МТЗ I>пуск)
		varDev.Add( 62117, new BCD_FieldMT( 1, this, false ));	//  (МТЗ I>откл)
		varDev.Add( 62118, new BCD_FieldMT( 1, this, false ));	//  (МТЗ I>сигн)
		varDev.Add( 62119, new BCD_FieldMT( 1, this, false ));	//  (МТЗ УСК)
		varDev.Add( 62120, new BCD_FieldMT( 1, this, false ));	//  (УРОВ)
		varDev.Add( 62121, new BCD_FieldMT( 1, this, false ));	//  (ЗОФ пуск)
		varDev.Add( 62122, new BCD_FieldMT( 1, this, false ));	//  (ЗОФ откл)
		varDev.Add( 62123, new BCD_FieldMT( 1, this, false ));	//  (O3З пуск)
		varDev.Add( 62124, new BCD_FieldMT( 1, this, false ));	//  (O3З откл)
		varDev.Add( 62125, new BCD_FieldMT( 1, this, false ));	//  (O3З сигн)
		varDev.Add( 62126, new BCD_FieldMT( 1, this, false ));	//  (ЗMН пуск)
		varDev.Add( 62127, new BCD_FieldMT( 1, this, false ));	//  (ЗMН откл)
		varDev.Add( 62128, new BCD_FieldMT( 1, this, false ));	//  (ЗMН сигн)
		varDev.Add( 62129, new BCD_FieldMT( 1, this, false ));	//  (ЗПП пуск)
		varDev.Add( 62130, new BCD_FieldMT( 1, this, false ));	//  (ЗПП откл)
		varDev.Add( 62131, new BCD_FieldMT( 1, this, false ));	//  (ЗПН пуск)
		varDev.Add( 62132, new BCD_FieldMT( 1, this, false ));	//  (ЗПН откл)
		varDev.Add( 62133, new BCD_FieldMT( 1, this, false ));	//  (ЗПН сигн)
		varDev.Add( 62134, new BCD_FieldMT( 1, this, false ));	//  (ЗCH пуск)
		varDev.Add( 62135, new BCD_FieldMT( 1, this, false ));	//  (ЗCH откл)
		varDev.Add( 62136, new BCD_FieldMT( 1, this, false ));	//  (АПВ 1 успеш)
		varDev.Add( 62137, new BCD_FieldMT( 1, this, false ));	//  (АПВ 2 успеш)
		varDev.Add( 62138, new BCD_FieldMT( 1, this, false ));	//  (АПВ 1 неуспеш)
		varDev.Add( 62139, new BCD_FieldMT( 1, this, false ));	//  (АПВ 2 неуспеш)
		varDev.Add( 62141, new DateTime3_FieldMT( 3, this, false ));	//  (Дата сброса накопительной информации.)
		varDev.Add( 165, new DateTime4_FieldMT( 4, this, false ));	// (Астрономическое время срабатывания выключателя)
		varDev.Add( 10332, new DateTime4_FieldMT( 4, this, false ));	// (Время аварии)
		varDev.Add( 62083, new Bit_FieldMT( 1, this, false ));	// (Программные ключи)
		varDev.Add( 62089, new Bit_FieldMT( 1, this, false ));	// (Программные ключи)
		varDev.Add( 62088, new Bit_FieldMT( 1, this, false ));	// (Программные ключи)
		ConfigureMF(ref varDev, "");
	}
	public override string	ToString()
	{
		return "BMRZ_KL_09_33_12";
	}
	public override void	ConfigureMF(ref Hashtable vD, string modfileName)
	{}
}
}

