using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
namespace NetCrzaDevices
{
/// <summary>
///     classBMRZ_KL_10_46_12
/// </summary>
public class BMRZ_KL_10_46_12 : BMRZ
{
	public BMRZ_KL_10_46_12(int nfc, int ndev, int size_memDev, string devname)
	{
		NFC			= nfc;
		NDev			= ndev;
		DeviceName	= devname;
		varDev		= new Hashtable();
		
		varDev.Add( 25, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 26, new Bit_FieldMT( 1, this, false ));	// (chanel19)
		varDev.Add( 27, new Bit_FieldMT( 1, this, false ));	// (chanel8)
		varDev.Add( 33, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia)
		varDev.Add( 34, new Int_FieldMT( 1, this, false ));	// (chanel1=Ib)
		varDev.Add( 35, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic)
		varDev.Add( 36, new Int_FieldMT( 1, this, false ));	// (chanel3=3Io)
		varDev.Add( 37, new Int_FieldMT( 1, this, false ));	// (chanel4=3Uo)
		varDev.Add( 38, new Int_FieldMT( 1, this, false ));	// (chanel5=Uab)
		varDev.Add( 39, new Int_FieldMT( 1, this, false ));	// (chanel6=Ubc)
		varDev.Add( 41, new Int_FieldMT( 1, this, false ));	// (chanel8=U2)
		varDev.Add( 42, new Int_FieldMT( 1, this, false ));	// (chanel9=I2)
		varDev.Add( 43, new Int_FieldMT( 1, this, false ));	// (chanel10=3Io вг)
		varDev.Add( 45, new Int_FieldMT( 1, this, false ));	// (chanel12)
		varDev.Add( 47, new Int_FieldMT( 1, this, false ));	// (chanel14)
		varDev.Add( 48, new Int_FieldMT( 1, this, false ));	// (chanel15)
		varDev.Add( 50, new Int_FieldMT( 1, this, false ));	// (chanel17=F)
		varDev.Add( 51, new Bit_FieldMT( 1, this, false ));	// (byte)
		varDev.Add( 10282, new Bit_FieldMT( 1, this, false ));	// (byte0_0)
		varDev.Add( 10283, new Bit_FieldMT( 1, this, false ));	// (byte2_0)
		varDev.Add( 10284, new Bit_FieldMT( 1, this, false ));	// (byte4_0)
		varDev.Add( 10285, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia)
		varDev.Add( 10286, new Int_FieldMT( 1, this, false ));	// (chanel1=Ib)
		varDev.Add( 10287, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic)
		varDev.Add( 10288, new Int_FieldMT( 1, this, false ));	// (chanel3=3Io)
		varDev.Add( 10289, new Int_FieldMT( 1, this, false ));	// (chanel4=3Uo)
		varDev.Add( 10290, new Int_FieldMT( 1, this, false ));	// (chanel5=Uab)
		varDev.Add( 10291, new Int_FieldMT( 1, this, false ));	// (chanel6=Ubc)
		varDev.Add( 10293, new Int_FieldMT( 1, this, false ));	// (chanel8=U2)
		varDev.Add( 10294, new Int_FieldMT( 1, this, false ));	// (chanel9=I2)
		varDev.Add( 10295, new Int_FieldMT( 1, this, false ));	// (chanel10=3Io вг)
		varDev.Add( 10297, new Int_FieldMT( 1, this, false ));	// (chanel12)
		varDev.Add( 10299, new Int_FieldMT( 1, this, false ));	// (chanel14)
		varDev.Add( 10300, new Int_FieldMT( 1, this, false ));	// (chanel15)
		varDev.Add( 10302, new Int_FieldMT( 1, this, false ));	// (chanel17=F)
		varDev.Add( 10303, new Bit_FieldMT( 1, this, false ));	// (Направления мощностей на омант срабатывания защит)
		varDev.Add( 10304, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia)
		varDev.Add( 10305, new Int_FieldMT( 1, this, false ));	// (chanel1=Ib)
		varDev.Add( 10306, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic)
		varDev.Add( 10307, new Int_FieldMT( 1, this, false ));	// (chanel3=3Io)
		varDev.Add( 10308, new Int_FieldMT( 1, this, false ));	// (chanel4=3Uo)
		varDev.Add( 10309, new Int_FieldMT( 1, this, false ));	// (chanel5=Uab)
		varDev.Add( 10310, new Int_FieldMT( 1, this, false ));	// (chanel6=Ubc)
		varDev.Add( 10312, new Int_FieldMT( 1, this, false ));	// (chanel8=U2)
		varDev.Add( 10313, new Int_FieldMT( 1, this, false ));	// (chanel9=I2)
		varDev.Add( 10314, new Int_FieldMT( 1, this, false ));	// (chanel10=3Io вг)
		varDev.Add( 10316, new Int_FieldMT( 1, this, false ));	// (chanel12)
		varDev.Add( 10318, new Int_FieldMT( 1, this, false ));	// (chanel14)
		varDev.Add( 10319, new Int_FieldMT( 1, this, false ));	// (chanel15)
		varDev.Add( 10321, new Int_FieldMT( 1, this, false ));	// (chanel17=F)
		varDev.Add( 10322, new Bit_FieldMT( 1, this, false ));	// (Направления мощностей на момент пуска защит)
		varDev.Add( 10323, new UInt_FieldMT( 1, this, false ));	// ()
		varDev.Add( 10324, new UInt_FieldMT( 1, this, false ));	// ()
		varDev.Add( 10325, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 10326, new Bit_FieldMT( 1, this, false ));	// (chanel19)
		varDev.Add( 10327, new Bit_FieldMT( 1, this, false ));	// (chanel8)
		varDev.Add( 10328, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 10329, new Bit_FieldMT( 1, this, false ));	// (chanel19)
		varDev.Add( 10330, new Bit_FieldMT( 1, this, false ));	// (chanel8)
		varDev.Add( 10332, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 62006, new BCDPack_FieldMT( 1, this, false ));	// (Ustav0=9,"МТЗ Tуск)
		varDev.Add( 62007, new BCDPack_FieldMT( 1, this, false ));	// (Ustav1=5,"ЗОФ I2>)
		varDev.Add( 62008, new BCDPack_FieldMT( 1, this, false ));	// (Ustav2=5,"ЗОФ Tзоф)
		varDev.Add( 62009, new BCDPack_FieldMT( 1, this, false ));	// (Ustav3=9,"УРОВ Tуров)
		varDev.Add( 62010, new BCDPack_FieldMT( 1, this, false ));	// (Ustav4=9,"АПВ Tапв1)
		varDev.Add( 62011, new BCDPack_FieldMT( 1, this, false ));	// (Ustav5=9,"АПВ Tапв2)
		varDev.Add( 62012, new BCDPack_FieldMT( 1, this, false ));	// (Ustav6=8,"ЧАПВ Тчапв)
		varDev.Add( 62013, new BCDPack_FieldMT( 1, this, false ));	// (Ustav7=8,"АЧР Тачр)
		varDev.Add( 62014, new BCDPack_FieldMT( 1, this, false ));	// (Ustav8=4,"ЗПП Fзпп<)
		varDev.Add( 62015, new BCDPack_FieldMT( 1, this, false ));	// (Ustav9=4,"ЗПП Tзпп)
		varDev.Add( 62016, new BCDPack_FieldMT( 1, this, false ));	// (Ustav10=6,"ЗМН U<)
		varDev.Add( 62017, new BCDPack_FieldMT( 1, this, false ));	// (Ustav11=6,"ЗМН U2>)
		varDev.Add( 62018, new BCDPack_FieldMT( 1, this, false ));	// (Ustav12=6,"ЗМН Тзмн)
		varDev.Add( 62019, new BCDPack_FieldMT( 1, this, false ));	// (Ustav13=7,"ЗПН U>)
		varDev.Add( 62020, new BCDPack_FieldMT( 1, this, false ));	// (Ustav14=7,"ЗПН U2>)
		varDev.Add( 62021, new BCDPack_FieldMT( 1, this, false ));	// (Ustav15=7,"ЗПН Тзпн)
		varDev.Add( 62022, new BCDPack_FieldMT( 1, this, false ));	// (Ustav16=4,"ДН Фф)
		varDev.Add( 62023, new BCDPack_FieldMT( 1, this, false ));	// (Ustav17=9,"ДН Фо)
		varDev.Add( 62024, new BCDPack_FieldMT( 1, this, false ));	// (Ustav18=0,"МТЗ I>>>)
		varDev.Add( 62025, new BCDPack_FieldMT( 1, this, false ));	// (Ustav19=0,"МТЗ I>>)
		varDev.Add( 62026, new BCDPack_FieldMT( 1, this, false ));	// (Ustav20=0,"МТЗ I>нез)
		varDev.Add( 62027, new BCDPack_FieldMT( 1, this, false ));	// (Ustav21=0,"МТЗ I>зав)
		varDev.Add( 62028, new BCDPack_FieldMT( 1, this, false ));	// (Ustav22=0,"МТЗ T>>>)
		varDev.Add( 62029, new BCDPack_FieldMT( 1, this, false ));	// (Ustav23=0,"МТЗ T>>)
		varDev.Add( 62030, new BCDPack_FieldMT( 1, this, false ));	// (Ustav24=0,"МТЗ Tнез>)
		varDev.Add( 62031, new BCDPack_FieldMT( 1, this, false ));	// (Ustav25=0,"МТЗ Tзав>)
		varDev.Add( 62032, new BCDPack_FieldMT( 1, this, false ));	// (Ustav26=2,"ОЗЗ 3Uo>)
		varDev.Add( 62033, new BCDPack_FieldMT( 1, this, false ));	// (Ustav27=2,"ОЗЗ 3Io>)
		varDev.Add( 62034, new BCDPack_FieldMT( 1, this, false ));	// (Ustav28=2,"ОЗЗ Tозз1)
		varDev.Add( 62035, new BCDPack_FieldMT( 1, this, false ));	// (Ustav29=2,"ОЗЗ Tозз2)
		varDev.Add( 62036, new BCDPack_FieldMT( 1, this, false ));	// (Ustav30=1,"МТЗ I>>>)
		varDev.Add( 62037, new BCDPack_FieldMT( 1, this, false ));	// (Ustav31=1,"МТЗ I>>)
		varDev.Add( 62038, new BCDPack_FieldMT( 1, this, false ));	// (Ustav32=1,"МТЗ I>нез)
		varDev.Add( 62039, new BCDPack_FieldMT( 1, this, false ));	// (Ustav33=1,"МТЗ I>зав)
		varDev.Add( 62040, new BCDPack_FieldMT( 1, this, false ));	// (Ustav34=1,"МТЗ T>>>)
		varDev.Add( 62041, new BCDPack_FieldMT( 1, this, false ));	// (Ustav35=1,"МТЗ T>>)
		varDev.Add( 62042, new BCDPack_FieldMT( 1, this, false ));	// (Ustav36=1,"МТЗ Tнез>)
		varDev.Add( 62043, new BCDPack_FieldMT( 1, this, false ));	// (Ustav37=1,"МТЗ Tзав>)
		varDev.Add( 62044, new BCDPack_FieldMT( 1, this, false ));	// (Ustav38=3,"ОЗЗ 3Uo>)
		varDev.Add( 62045, new BCDPack_FieldMT( 1, this, false ));	// (Ustav39=3,"ОЗЗ 3Io>)
		varDev.Add( 62046, new BCDPack_FieldMT( 1, this, false ));	// (Ustav40=3,"ОЗЗ Tозз1)
		varDev.Add( 62047, new BCDPack_FieldMT( 1, this, false ));	// (Ustav41=3,"ОЗЗ Tозз2)
		varDev.Add( 62048, new Bit_FieldMT( 1, this, false ));	// (Config0_0)
		varDev.Add( 62049, new Bit_FieldMT( 1, this, false ));	// (Config2_1)
		varDev.Add( 62050, new Bit_FieldMT( 1, this, false ));	// (Config4_1)
		varDev.Add( 62051, new Bit_FieldMT( 1, this, false ));	// (Config8_0)
		varDev.Add( 62052, new Bit_FieldMT( 1, this, false ));	// (Config10_1)
		varDev.Add( 62002, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 62057, new BCD_FieldMT( 1, this, false ));	// ()
		varDev.Add( 62056, new BCD_FieldMT( 1, this, false ));	// ()
		varDev.Add( 62058, new BCD_FieldMT( 1, this, false ));	// ()
		varDev.Add( 28, new Bit_FieldMT( 1, this, false ));	// (byte0_0)
		varDev.Add( 62111, new BCD_FieldMT( 1, this, false ));	// (Count0)
		varDev.Add( 62112, new BCD_FieldMT( 1, this, false ));	// (Count1)
		varDev.Add( 62113, new BCD_FieldMT( 1, this, false ));	// (Count2)
		varDev.Add( 62114, new BCD_FieldMT( 1, this, false ));	// (Count3)
		varDev.Add( 62115, new BCD_FieldMT( 1, this, false ));	// (Count4)
		varDev.Add( 62116, new BCD_FieldMT( 1, this, false ));	// (Count5)
		varDev.Add( 62117, new BCD_FieldMT( 1, this, false ));	// (Count6)
		varDev.Add( 62118, new BCD_FieldMT( 1, this, false ));	// (Count7)
		varDev.Add( 62119, new BCD_FieldMT( 1, this, false ));	// (Count8)
		varDev.Add( 62120, new BCD_FieldMT( 1, this, false ));	// (Count9)
		varDev.Add( 62121, new BCD_FieldMT( 1, this, false ));	// (Count10)
		varDev.Add( 62122, new BCD_FieldMT( 1, this, false ));	// (Count11)
		varDev.Add( 62123, new BCD_FieldMT( 1, this, false ));	// (Count12)
		varDev.Add( 62124, new BCD_FieldMT( 1, this, false ));	// (Count13)
		varDev.Add( 62125, new BCD_FieldMT( 1, this, false ));	// (Count14)
		varDev.Add( 62126, new BCD_FieldMT( 1, this, false ));	// (Count15)
		varDev.Add( 62127, new BCD_FieldMT( 1, this, false ));	// (Count16)
		varDev.Add( 62128, new BCD_FieldMT( 1, this, false ));	// (Count17)
		varDev.Add( 62129, new BCD_FieldMT( 1, this, false ));	// (Count18)
		varDev.Add( 62130, new BCD_FieldMT( 1, this, false ));	// (Count19)
		varDev.Add( 62131, new BCD_FieldMT( 1, this, false ));	// (Count20)
		varDev.Add( 62132, new BCD_FieldMT( 1, this, false ));	// (Count21)
		varDev.Add( 62133, new BCD_FieldMT( 1, this, false ));	// (Count22)
		varDev.Add( 62134, new BCD_FieldMT( 1, this, false ));	// (Count23)
		varDev.Add( 62135, new BCD_FieldMT( 1, this, false ));	// (Count24)
		varDev.Add( 62136, new BCD_FieldMT( 1, this, false ));	// (Count25)
		varDev.Add( 62137, new BCD_FieldMT( 1, this, false ));	// (Count26)
		varDev.Add( 62102, new Real_FieldMT( 2, this, false ));	// ()
		varDev.Add( 62104, new Real_FieldMT( 2, this, false ));	// ()
		varDev.Add( 62106, new Real_FieldMT( 2, this, false ));	// ()
		varDev.Add( 62108, new Int_FieldMT( 1, this, false ));	// ()
		varDev.Add( 62109, new Int_FieldMT( 1, this, false ));	// ()
		varDev.Add( 62110, new Int_FieldMT( 1, this, false ));	// ()
		varDev.Add( 62138, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 0, new BCD_FieldMT( 1, this, false ));	// (Reg_Block_ID)
		varDev.Add( 1, new Stringz_FieldMT( 16, this, false ));	// (Reg_Slave_ID)
		varDev.Add( 17, new BCD_FieldMT( 1, this, false ));	// (Reg_Version)
		varDev.Add( 19, new DateTime4_FieldMT( 4, this, false ));	// (Reg_Time)
		varDev.Add( 23, new UInt_FieldMT( 1, this, false ));	// (Reg_Status_Cnt)
		varDev.Add( 24, new Bit_FieldMT( 1, this, false ));	// (Reg_Status)
		varDev.Add( 30, new Bit_FieldMT( 1, this, false ));	// (Reg_Err)
		varDev.Add( 32, new Bit_FieldMT( 1, this, false ));	// (Reg_Err)
		varDev.Add( 139, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 140, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 141, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 142, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 143, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 144, new Int_FieldMT( 1, this, false ));	// (Reg_Max_Time_BYKL)
		varDev.Add( 145, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign1)
		varDev.Add( 149, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign2)
		varDev.Add( 153, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign3)
		varDev.Add( 157, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign4)
		varDev.Add( 161, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign5)
		varDev.Add( 165, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_BYKL)
		varDev.Add( 169, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_Sbros)
		varDev.Add( 60001, new Bit_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60002, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60003, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60004, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60005, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60006, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60007, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60008, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60009, new DateTimeUTC_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60011, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60012, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60013, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60014, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60015, new Stringz_FieldMT( 17, this, false ));	// (null)
		varDev.Add( 60050, new UDInt_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60052, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60053, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60054, new DateTimeUTC_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60056, new Int_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60057, new Int_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60058, new Stringz_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60060, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60061, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 195, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 197, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 199, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 201, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 203, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 205, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 207, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 209, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 211, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 213, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 215, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 217, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 219, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 221, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 223, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 225, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 227, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 229, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10376, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10378, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10380, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10382, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10384, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10386, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10388, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10390, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10392, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10394, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10396, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10398, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10400, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10402, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10404, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10406, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10408, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10410, new Real_FieldMT( 2, this, false ));	// (null)
		ConfigureMF(ref varDev, "");
	}
	public override string	ToString()
	{
		return "BMRZ_KL_10_46_12";
	}
	public override void	ConfigureMF(ref Hashtable vD, string modfileName)
	{}
}
}

