using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
namespace NetCrzaDevices
{
/// <summary>
///     classBMRZ_TP_BH_30_11
/// </summary>
public class BMRZ_TP_BH_30_11 : BMRZ
{
	public BMRZ_TP_BH_30_11(int nfc, int ndev, int size_memDev, string devname)
	{
		NFC			= nfc;
		NDev			= ndev;
		DeviceName	= devname;
		varDev		= new Hashtable();
		
		varDev.Add( 58, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 59, new Bit_FieldMT( 1, this, false ));	// (chanel16)
		varDev.Add( 64, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 65, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 33, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia ВН)
		varDev.Add( 34, new Int_FieldMT( 1, this, false ));	// (chanel1=Iв ВН)
		varDev.Add( 35, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic ВН)
		varDev.Add( 36, new Int_FieldMT( 1, this, false ));	// (chanel3=Ia НН1)
		varDev.Add( 37, new Int_FieldMT( 1, this, false ));	// (chanel4=Iв НН1)
		varDev.Add( 38, new Int_FieldMT( 1, this, false ));	// (chanel5=Ic НН1)
		varDev.Add( 39, new Int_FieldMT( 1, this, false ));	// (chanel6=Ia НН2)
		varDev.Add( 40, new Int_FieldMT( 1, this, false ));	// (chanel7=Iв НН2)
		varDev.Add( 41, new Int_FieldMT( 1, this, false ));	// (chanel8=Ic НН2)
		varDev.Add( 42, new Int_FieldMT( 1, this, false ));	// (chanel9=3Io ВН)
		varDev.Add( 43, new Int_FieldMT( 1, this, false ));	// (chanel10=Ia ВН)
		varDev.Add( 44, new Int_FieldMT( 1, this, false ));	// (chanel11=Iв ВН)
		varDev.Add( 45, new Int_FieldMT( 1, this, false ));	// (chanel12=Ic ВН)
		varDev.Add( 46, new Int_FieldMT( 1, this, false ));	// (chanel13=Ia НН1)
		varDev.Add( 47, new Int_FieldMT( 1, this, false ));	// (chanel14=Iв НН1)
		varDev.Add( 48, new Int_FieldMT( 1, this, false ));	// (chanel15=Ic НН1)
		varDev.Add( 49, new Int_FieldMT( 1, this, false ));	// (chanel16=Ia НН2)
		varDev.Add( 50, new Int_FieldMT( 1, this, false ));	// (chanel17=Iв НН2)
		varDev.Add( 51, new Int_FieldMT( 1, this, false ));	// (chanel18=Ic НН2)
		varDev.Add( 52, new Int_FieldMT( 1, this, false ));	// (chanel19=3Io ВН)
		varDev.Add( 53, new Int_FieldMT( 1, this, false ));	// (chanel20=F)
		varDev.Add( 10282, new Bit_FieldMT( 1, this, false ));	// (byte0_0)
		varDev.Add( 10283, new Bit_FieldMT( 1, this, false ));	// (byte2_4)
		varDev.Add( 10284, new Bit_FieldMT( 1, this, false ));	// (byte4_0)
		varDev.Add( 10285, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia ВН)
		varDev.Add( 10286, new Int_FieldMT( 1, this, false ));	// (chanel1=Iв ВН)
		varDev.Add( 10287, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic ВН)
		varDev.Add( 10288, new Int_FieldMT( 1, this, false ));	// (chanel3=Ia НН1)
		varDev.Add( 10289, new Int_FieldMT( 1, this, false ));	// (chanel4=Iв НН1)
		varDev.Add( 10290, new Int_FieldMT( 1, this, false ));	// (chanel5=Ic НН1)
		varDev.Add( 10291, new Int_FieldMT( 1, this, false ));	// (chanel6=Ia НН2)
		varDev.Add( 10292, new Int_FieldMT( 1, this, false ));	// (chanel7=Iв НН2)
		varDev.Add( 10293, new Int_FieldMT( 1, this, false ));	// (chanel8=Ic НН2)
		varDev.Add( 10294, new Int_FieldMT( 1, this, false ));	// (chanel9=3Io ВН)
		varDev.Add( 10295, new Int_FieldMT( 1, this, false ));	// (chanel10=Ia ВН)
		varDev.Add( 10296, new Int_FieldMT( 1, this, false ));	// (chanel11=Iв ВН)
		varDev.Add( 10297, new Int_FieldMT( 1, this, false ));	// (chanel12=Ic ВН)
		varDev.Add( 10298, new Int_FieldMT( 1, this, false ));	// (chanel13=Ia НН1)
		varDev.Add( 10299, new Int_FieldMT( 1, this, false ));	// (chanel14=Iв НН1)
		varDev.Add( 10300, new Int_FieldMT( 1, this, false ));	// (chanel15=Ic НН1)
		varDev.Add( 10301, new Int_FieldMT( 1, this, false ));	// (chanel16=Ia НН2)
		varDev.Add( 10302, new Int_FieldMT( 1, this, false ));	// (chanel17=Iв НН2)
		varDev.Add( 10303, new Int_FieldMT( 1, this, false ));	// (chanel18=Ic НН2)
		varDev.Add( 10304, new Int_FieldMT( 1, this, false ));	// (chanel19=3Io ВН)
		varDev.Add( 10305, new Int_FieldMT( 1, this, false ));	// (chanel20=F)
		varDev.Add( 10306, new Bit_FieldMT( 1, this, false ));	// (Reg_Valid)
		varDev.Add( 10307, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia ВН)
		varDev.Add( 10308, new Int_FieldMT( 1, this, false ));	// (chanel1=Iв ВН)
		varDev.Add( 10309, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic ВН)
		varDev.Add( 10310, new Int_FieldMT( 1, this, false ));	// (chanel3=Ia НН1)
		varDev.Add( 10311, new Int_FieldMT( 1, this, false ));	// (chanel4=Iв НН1)
		varDev.Add( 10312, new Int_FieldMT( 1, this, false ));	// (chanel5=Ic НН1)
		varDev.Add( 10313, new Int_FieldMT( 1, this, false ));	// (chanel6=Ia НН2)
		varDev.Add( 10314, new Int_FieldMT( 1, this, false ));	// (chanel7=Iв НН2)
		varDev.Add( 10315, new Int_FieldMT( 1, this, false ));	// (chanel8=Ic НН2)
		varDev.Add( 10316, new Int_FieldMT( 1, this, false ));	// (chanel9=3Io ВН)
		varDev.Add( 10317, new Int_FieldMT( 1, this, false ));	// (chanel10=Ia ВН)
		varDev.Add( 10318, new Int_FieldMT( 1, this, false ));	// (chanel11=Iв ВН)
		varDev.Add( 10319, new Int_FieldMT( 1, this, false ));	// (chanel12=Ic ВН)
		varDev.Add( 10320, new Int_FieldMT( 1, this, false ));	// (chanel13=Ia НН1)
		varDev.Add( 10321, new Int_FieldMT( 1, this, false ));	// (chanel14=Iв НН1)
		varDev.Add( 10322, new Int_FieldMT( 1, this, false ));	// (chanel15=Ic НН1)
		varDev.Add( 10323, new Int_FieldMT( 1, this, false ));	// (chanel16=Ia НН2)
		varDev.Add( 10324, new Int_FieldMT( 1, this, false ));	// (chanel17=Iв НН2)
		varDev.Add( 10325, new Int_FieldMT( 1, this, false ));	// (chanel18=Ic НН2)
		varDev.Add( 10326, new Int_FieldMT( 1, this, false ));	// (chanel19=3Io ВН)
		varDev.Add( 10327, new Int_FieldMT( 1, this, false ));	// (chanel20=F)
		varDev.Add( 10328, new Bit_FieldMT( 1, this, false ));	// (Reg_Valid)
		varDev.Add( 10329, new UInt_FieldMT( 1, this, false ));	// ()
		varDev.Add( 10330, new UInt_FieldMT( 1, this, false ));	// ()
		varDev.Add( 10331, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 10332, new Bit_FieldMT( 1, this, false ));	// (chanel16)
		varDev.Add( 10333, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 10334, new Bit_FieldMT( 1, this, false ));	// (chanel17)
		varDev.Add( 10335, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 10336, new Bit_FieldMT( 1, this, false ));	// (chanel16)
		varDev.Add( 10337, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 10338, new Bit_FieldMT( 1, this, false ));	// (chanel17)
		varDev.Add( 10340, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 62006, new BCDPack_FieldMT( 1, this, false ));	// (Ustav0)
		varDev.Add( 62007, new BCDPack_FieldMT( 1, this, false ));	// (Ustav1=0,"МТЗ ВH Т1)
		varDev.Add( 62008, new BCDPack_FieldMT( 1, this, false ));	// (Ustav2=0,"МТЗ ВH Т2)
		varDev.Add( 62009, new BCDPack_FieldMT( 1, this, false ));	// (Ustav3)
		varDev.Add( 62010, new BCDPack_FieldMT( 1, this, false ));	// (Ustav4=0,"МТЗ НH1 Т1(откл.НН1))
		varDev.Add( 62011, new BCDPack_FieldMT( 1, this, false ));	// (Ustav5=0,"МТЗ НH1 Т2(откл.Т))
		varDev.Add( 62012, new BCDPack_FieldMT( 1, this, false ));	// (Ustav6=0,"МТЗ НH1 Туск)
		varDev.Add( 62013, new BCDPack_FieldMT( 1, this, false ));	// (Ustav7)
		varDev.Add( 62014, new BCDPack_FieldMT( 1, this, false ));	// (Ustav8=0,"МТЗ НH2 Т1(откл.НН2))
		varDev.Add( 62015, new BCDPack_FieldMT( 1, this, false ));	// (Ustav9=0,"МТЗ НH2 Т2(откл.Т))
		varDev.Add( 62016, new BCDPack_FieldMT( 1, this, false ));	// (Ustav10=0,"МТЗ НH2 Туск.)
		varDev.Add( 62017, new BCDPack_FieldMT( 1, this, false ));	// (Ustav11=0,"Iуров НН)
		varDev.Add( 62018, new BCDPack_FieldMT( 1, this, false ));	// (Ustav12=0,"МТЗ НН1 Тлзш)
		varDev.Add( 62019, new BCDPack_FieldMT( 1, this, false ));	// (Ustav13=0,"МТЗ НН2 Тлзш)
		varDev.Add( 62020, new BCDPack_FieldMT( 1, this, false ));	// (Ustav14)
		varDev.Add( 62021, new BCDPack_FieldMT( 1, this, false ));	// (Ustav15=0,"ТЗНП Т1тзнп)
		varDev.Add( 62022, new BCDPack_FieldMT( 1, this, false ));	// (Ustav16=0,"ТЗНП Т2тзнп)
		varDev.Add( 62023, new BCDPack_FieldMT( 1, this, false ));	// (Ustav17=0,"ТЗНП Т3тзнп)
		varDev.Add( 62024, new BCDPack_FieldMT( 1, this, false ));	// (Ustav18=0,"ТЗНП Т4тзнп)
		varDev.Add( 62025, new BCDPack_FieldMT( 1, this, false ));	// (Ustav19=1,"Iпер.ВН)
		varDev.Add( 62026, new BCDPack_FieldMT( 1, this, false ));	// (Ustav20=1,"Iпер.НН)
		varDev.Add( 62027, new BCDPack_FieldMT( 1, this, false ));	// (Ustav21=1,"Тперегрузки)
		varDev.Add( 62028, new BCDPack_FieldMT( 1, this, false ));	// (Ustav22=1,"Iблок.РПН)
		varDev.Add( 62029, new BCDPack_FieldMT( 1, this, false ));	// (Ustav23=1,"Тблок.РПН)
		varDev.Add( 62030, new BCDPack_FieldMT( 1, this, false ));	// (Ustav24=1,"Iобдува ВН)
		varDev.Add( 62031, new BCDPack_FieldMT( 1, this, false ));	// (Ustav25=1,"Iобдува НН)
		varDev.Add( 62032, new BCDPack_FieldMT( 1, this, false ));	// (Ustav26=1,"Тобдува)
		varDev.Add( 62033, new BCDPack_FieldMT( 1, this, false ));	// (Ustav27=1,"Iуров ВН)
		varDev.Add( 62034, new BCDPack_FieldMT( 1, this, false ));	// (Ustav28=1,"Tуров ВН)
		varDev.Add( 62035, new BCDPack_FieldMT( 1, this, false ));	// (Ustav29=1,"Tапв 1)
		varDev.Add( 62036, new BCDPack_FieldMT( 1, this, false ));	// (Ustav30=1,"Tапв 2)
		varDev.Add( 62037, new BCDPack_FieldMT( 1, this, false ));	// (Ustav31=1,"Тзав.пруж.)
		varDev.Add( 62038, new BCDPack_FieldMT( 1, this, false ));	// (Ustav32=1,"Тзащ.ЭМ)
		varDev.Add( 62039, new BCDPack_FieldMT( 1, this, false ));	// (Ustav33=2,"Iн.ВН)
		varDev.Add( 62040, new BCDPack_FieldMT( 1, this, false ));	// (Ustav34=2,"Iн.НН)
		varDev.Add( 62041, new BCDPack_FieldMT( 1, this, false ));	// (Ustav35=2,"Iперв.ТТ ВН)
		varDev.Add( 62042, new UInt_FieldMT( 1, this, false ));	// (Ustav36=2,"Iвтор.ТТ ВН)
		varDev.Add( 62043, new BCDPack_FieldMT( 1, this, false ));	// (Ustav37=2,"Iперв.ТТ НН)
		varDev.Add( 62044, new UInt_FieldMT( 1, this, false ));	// (Ustav38=2,"Iвтор.ТТ НН)
		varDev.Add( 62045, new UInt_FieldMT( 1, this, false ));	// (Ustav39=2,"Iн.ПИТ ВH)
		varDev.Add( 62046, new UInt_FieldMT( 1, this, false ));	// (Ustav40=2,"Iн.ПИТ НH)
		varDev.Add( 62047, new UInt_FieldMT( 1, this, false ));	// (Ustav41=2,"Конт.выход 1)
		varDev.Add( 62048, new UInt_FieldMT( 1, this, false ));	// (Ustav42=2,"Конт.выход 2)
		varDev.Add( 62049, new Bit_FieldMT( 1, this, false ));	// (Config0_0)
		varDev.Add( 62050, new Bit_FieldMT( 1, this, false ));	// (Config3_0)
		varDev.Add( 62002, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 28, new Bit_FieldMT( 1, this, false ));	// (byte0_0)
		varDev.Add( 70, new Bit_FieldMT( 1, this, false ));	// (Chanel0)
		varDev.Add( 71, new Bit_FieldMT( 1, this, false ));	// (Chanel16)
		varDev.Add( 0, new BCD_FieldMT( 1, this, false ));	// (Reg_Block_ID)
		varDev.Add( 1, new Stringz_FieldMT( 16, this, false ));	// (Reg_Slave_ID)
		varDev.Add( 17, new BCD_FieldMT( 1, this, false ));	// (Reg_Version)
		varDev.Add( 19, new DateTime4_FieldMT( 4, this, false ));	// (Reg_Time)
		varDev.Add( 23, new UInt_FieldMT( 1, this, false ));	// (Reg_Status_Cnt)
		varDev.Add( 24, new Bit_FieldMT( 1, this, false ));	// (Reg_Status)
		varDev.Add( 30, new Bit_FieldMT( 1, this, false ));	// (Reg_Err)
		varDev.Add( 32, new Bit_FieldMT( 1, this, false ));	// (Reg_Err)
		varDev.Add( 139, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 140, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 141, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 144, new Int_FieldMT( 1, this, false ));	// (Reg_Max_Time_BYKL)
		varDev.Add( 145, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign1)
		varDev.Add( 149, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign2)
		varDev.Add( 153, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign3)
		varDev.Add( 165, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_BYKL)
		varDev.Add( 169, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_Sbros)
		varDev.Add( 60001, new Bit_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60002, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60003, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60004, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60005, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60006, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60007, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60008, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60009, new DateTimeUTC_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60011, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60012, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60013, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60014, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60015, new Stringz_FieldMT( 17, this, false ));	// (null)
		varDev.Add( 60050, new UDInt_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60052, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60053, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60054, new DateTimeUTC_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60056, new Int_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60057, new Int_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60058, new Stringz_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60060, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60061, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 195, new Real_FieldMT( 2, this, false ));	// (chanel0=Ia ВН)
		varDev.Add( 197, new Real_FieldMT( 2, this, false ));	// (chanel1=Iв ВН)
		varDev.Add( 199, new Real_FieldMT( 2, this, false ));	// (chanel2=Ic ВН)
		varDev.Add( 201, new Real_FieldMT( 2, this, false ));	// (chanel3=Ia НН1)
		varDev.Add( 203, new Real_FieldMT( 2, this, false ));	// (chanel4=Iв НН1)
		varDev.Add( 205, new Real_FieldMT( 2, this, false ));	// (chanel5=Ic НН1)
		varDev.Add( 207, new Real_FieldMT( 2, this, false ));	// (chanel6=Ia НН2)
		varDev.Add( 209, new Real_FieldMT( 2, this, false ));	// (chanel7=Iв НН2)
		varDev.Add( 211, new Real_FieldMT( 2, this, false ));	// (chanel8=Ic НН2)
		varDev.Add( 213, new Real_FieldMT( 2, this, false ));	// (chanel9=3Io ВН)
		varDev.Add( 215, new Real_FieldMT( 2, this, false ));	// (chanel10=Ia ВН)
		varDev.Add( 217, new Real_FieldMT( 2, this, false ));	// (chanel11=Iв ВН)
		varDev.Add( 219, new Real_FieldMT( 2, this, false ));	// (chanel12=Ic ВН)
		varDev.Add( 221, new Real_FieldMT( 2, this, false ));	// (chanel13=Ia НН1)
		varDev.Add( 223, new Real_FieldMT( 2, this, false ));	// (chanel14=Iв НН1)
		varDev.Add( 225, new Real_FieldMT( 2, this, false ));	// (chanel15=Ic НН1)
		varDev.Add( 227, new Real_FieldMT( 2, this, false ));	// (chanel16=Ia НН2)
		varDev.Add( 229, new Real_FieldMT( 2, this, false ));	// (chanel17=Iв НН2)
		varDev.Add( 231, new Real_FieldMT( 2, this, false ));	// (chanel18=Ic НН2)
		varDev.Add( 233, new Real_FieldMT( 2, this, false ));	// (chanel19=3Io ВН)
		varDev.Add( 235, new Real_FieldMT( 2, this, false ));	// (chanel20=F)
		varDev.Add( 62112, new BCD_FieldMT( 1, this, false ));	// (Count0)
		varDev.Add( 62113, new BCD_FieldMT( 1, this, false ));	// (Count1)
		varDev.Add( 62114, new BCD_FieldMT( 1, this, false ));	// (Count2)
		varDev.Add( 62115, new BCD_FieldMT( 1, this, false ));	// (Count3)
		varDev.Add( 62116, new BCD_FieldMT( 1, this, false ));	// (Count4)
		varDev.Add( 62117, new BCD_FieldMT( 1, this, false ));	// (Count5)
		varDev.Add( 62118, new BCD_FieldMT( 1, this, false ));	// (Count6)
		varDev.Add( 62119, new BCD_FieldMT( 1, this, false ));	// (Count7)
		varDev.Add( 62120, new BCD_FieldMT( 1, this, false ));	// (Count8)
		varDev.Add( 62121, new BCD_FieldMT( 1, this, false ));	// (Count9)
		varDev.Add( 62122, new BCD_FieldMT( 1, this, false ));	// (Count10)
		varDev.Add( 62123, new BCD_FieldMT( 1, this, false ));	// (Count11)
		varDev.Add( 62124, new BCD_FieldMT( 1, this, false ));	// (Count12)
		varDev.Add( 62125, new BCD_FieldMT( 1, this, false ));	// (Count13)
		varDev.Add( 62126, new BCD_FieldMT( 1, this, false ));	// (Count14)
		varDev.Add( 62127, new BCD_FieldMT( 1, this, false ));	// (Count15)
		varDev.Add( 62128, new BCD_FieldMT( 1, this, false ));	// (Count16)
		varDev.Add( 62129, new BCD_FieldMT( 1, this, false ));	// (Count17)
		varDev.Add( 62130, new BCD_FieldMT( 1, this, false ));	// (Count18)
		varDev.Add( 62131, new BCD_FieldMT( 1, this, false ));	// (Count19)
		varDev.Add( 62132, new BCD_FieldMT( 1, this, false ));	// (Count20)
		varDev.Add( 62133, new BCD_FieldMT( 1, this, false ));	// (Count21)
		varDev.Add( 62134, new BCD_FieldMT( 1, this, false ));	// (Count22)
		varDev.Add( 62135, new BCD_FieldMT( 1, this, false ));	// (Count23)
		varDev.Add( 62136, new BCD_FieldMT( 1, this, false ));	// (Count24)
		varDev.Add( 62137, new BCD_FieldMT( 1, this, false ));	// (Count25)
		varDev.Add( 62138, new BCD_FieldMT( 1, this, false ));	// (Count26)
		varDev.Add( 62139, new BCD_FieldMT( 1, this, false ));	// (Count27)
		varDev.Add( 62140, new BCD_FieldMT( 1, this, false ));	// (Count28)
		varDev.Add( 62141, new BCD_FieldMT( 1, this, false ));	// (Count29)
		varDev.Add( 62142, new BCD_FieldMT( 1, this, false ));	// (Count30)
		varDev.Add( 62102, new Real_FieldMT( 2, this, false ));	// ()
		varDev.Add( 62104, new Real_FieldMT( 2, this, false ));	// ()
		varDev.Add( 62106, new Real_FieldMT( 2, this, false ));	// ()
		varDev.Add( 62108, new Int_FieldMT( 1, this, false ));	// ()
		varDev.Add( 62109, new Int_FieldMT( 1, this, false ));	// ()
		varDev.Add( 62110, new Int_FieldMT( 1, this, false ));	// ()
		varDev.Add( 62143, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 10386, new Real_FieldMT( 2, this, false ));	// (chanel0=Ia ВН)
		varDev.Add( 10388, new Real_FieldMT( 2, this, false ));	// (chanel1=Iв ВН)
		varDev.Add( 10390, new Real_FieldMT( 2, this, false ));	// (chanel2=Ic ВН)
		varDev.Add( 10392, new Real_FieldMT( 2, this, false ));	// (chanel3=Ia НН1)
		varDev.Add( 10394, new Real_FieldMT( 2, this, false ));	// (chanel4=Iв НН1)
		varDev.Add( 10396, new Real_FieldMT( 2, this, false ));	// (chanel5=Ic НН1)
		varDev.Add( 10398, new Real_FieldMT( 2, this, false ));	// (chanel6=Ia НН2)
		varDev.Add( 10400, new Real_FieldMT( 2, this, false ));	// (chanel7=Iв НН2)
		varDev.Add( 10402, new Real_FieldMT( 2, this, false ));	// (chanel8=Ic НН2)
		varDev.Add( 10404, new Real_FieldMT( 2, this, false ));	// (chanel9=3Io ВН)
		varDev.Add( 10406, new Real_FieldMT( 2, this, false ));	// (chanel10=Ia ВН)
		varDev.Add( 10408, new Real_FieldMT( 2, this, false ));	// (chanel11=Iв ВН)
		varDev.Add( 10410, new Real_FieldMT( 2, this, false ));	// (chanel12=Ic ВН)
		varDev.Add( 10412, new Real_FieldMT( 2, this, false ));	// (chanel13=Ia НН1)
		varDev.Add( 10414, new Real_FieldMT( 2, this, false ));	// (chanel14=Iв НН1)
		varDev.Add( 10416, new Real_FieldMT( 2, this, false ));	// (chanel15=Ic НН1)
		varDev.Add( 10418, new Real_FieldMT( 2, this, false ));	// (chanel16=Ia НН2)
		varDev.Add( 10420, new Real_FieldMT( 2, this, false ));	// (chanel17=Iв НН2)
		varDev.Add( 10422, new Real_FieldMT( 2, this, false ));	// (chanel18=Ic НН2)
		varDev.Add( 10424, new Real_FieldMT( 2, this, false ));	// (chanel19=3Io ВН)
		varDev.Add( 10426, new Real_FieldMT( 2, this, false ));	// (chanel20=F)
		ConfigureMF(ref varDev, "");
	}
	public override string	ToString()
	{
		return "BMRZ_TP_BH_30_11";
	}
	public override void	ConfigureMF(ref Hashtable vD, string modfileName)
	{}
}
}



