using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
namespace NetCrzaDevices
{
/// <summary>
///     classBMRZ_KN_01_01_11
/// </summary>
public class BMRZ_KN_01_01_11 : BMRZ
{
	public BMRZ_KN_01_01_11(int nfc, int ndev, int size_memDev, string devname)
	{
		NFC			= nfc;
		NDev			= ndev;
		DeviceName	= devname;
		varDev		= new Hashtable();
		
		varDev.Add( 60000, new Bit_FieldMT( 1, this, false ));	//  (Регистр битовых флагов RTU)
		varDev.Add( 60001, new Bit_FieldMT( 1, this, false ));	//  ( )
		varDev.Add( 60002, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей аварий)
		varDev.Add( 60003, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей уставок)
		varDev.Add( 60004, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей осциллограмм)
		varDev.Add( 60005, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей максметра)
		varDev.Add( 60006, new UInt_FieldMT( 1, this, false ));	//  (Счетчик записей накопителя)
		varDev.Add( 60007, new UInt_FieldMT( 1, this, false ));	//  (Адрес на шине Modbus)
		varDev.Add( 60008, new UInt_FieldMT( 1, this, false ));	//  (Номер шины Modbus)
		varDev.Add( 60009, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата чтения по шине Modbus)
		varDev.Add( 60011, new UInt_FieldMT( 1, this, false ));	//  (Аргумент 1)
		varDev.Add( 60012, new UInt_FieldMT( 1, this, false ));	//  (Аргумент 2)
		varDev.Add( 60013, new UInt_FieldMT( 1, this, false ));	//  (Состояние протокола)
		varDev.Add( 60014, new UInt_FieldMT( 1, this, false ));	//  (Числовой идентификатор)
		varDev.Add( 60015, new Stringz_FieldMT( 17, this, false ));	//  (Текстовый идентификатор)
		varDev.Add( 0, new BCD_FieldMT( 1, this, false ));	//  (Номер конфигурации)
		varDev.Add( 1, new Stringz_FieldMT( 16, this, false ));	//  (Идентификатор)
		varDev.Add( 17, new BCD_FieldMT( 2, this, false ));	//  (Версия сетевого драйвера)
		varDev.Add( 19, new DateTime4_FieldMT( 4, this, false ));	//  (Текущее астрономич. время)
		varDev.Add( 23, new UInt_FieldMT( 1, this, false ));	//  (Счетчик изменения накопительной информации)
		varDev.Add( 60050, new UDInt_FieldMT( 2, this, false ));	//  (IP-адрес отправителя)
		varDev.Add( 60052, new UInt_FieldMT( 1, this, false ));	//  (Серия №)
		varDev.Add( 60053, new UInt_FieldMT( 1, this, false ));	//  (Пакет №)
		varDev.Add( 60054, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата поступления по часам ФК)
		varDev.Add( 60056, new Int_FieldMT( 1, this, false ));	//  (Причина отказа от выполнения)
		varDev.Add( 60057, new Int_FieldMT( 1, this, false ));	//  (Состояние выполнения команды)
		varDev.Add( 60058, new Stringz_FieldMT( 2, this, false ));	//  (Имя команды)
		varDev.Add( 60060, new UInt_FieldMT( 1, this, false ));	//  (Первый параметр команды)
		varDev.Add( 60061, new UInt_FieldMT( 1, this, false ));	//  (Второй параметр команды)
		varDev.Add( 24, new Bit_FieldMT( 1, this, false ));	//  (Слово статуса)
		varDev.Add( 25, new Bit_FieldMT( 1, this, false ));	//  (Входные дискретные сигналы)
		varDev.Add( 26, new Bit_FieldMT( 1, this, false ));	//  (Входные/выходные  дискретные сигналы)
		varDev.Add( 27, new Bit_FieldMT( 1, this, false ));	//  (Выходные  дискретные сигналы)
		varDev.Add( 28, new Bit_FieldMT( 1, this, false ));	//  (Cлово состояния сигнала Вызов)
		varDev.Add( 30, new Bit_FieldMT( 1, this, false ));	//  (Слово состояния неисправности БМРЗ)
		varDev.Add( 32, new Bit_FieldMT( 1, this, false ));	//  (Слово состояния неисправности БМРЗ)
		varDev.Add( 33, new Int_FieldMT( 1, this, false ));	// В(Uao=)
		varDev.Add( 34, new Int_FieldMT( 1, this, false ));	// В(Ubo=)
		varDev.Add( 35, new Int_FieldMT( 1, this, false ));	// В(Uco=)
		varDev.Add( 36, new Int_FieldMT( 1, this, false ));	// А(I2=)
		varDev.Add( 37, new Int_FieldMT( 1, this, false ));	// В(3Uo=)
		varDev.Add( 38, new Int_FieldMT( 1, this, false ));	// А(I1=)
		varDev.Add( 41, new Int_FieldMT( 1, this, false ));	// B(U2)
		varDev.Add( 43, new Int_FieldMT( 1, this, false ));	// Гц(F=)
		varDev.Add( 139, new Int_FieldMT( 1, this, false ));	//  (Ua0)
		varDev.Add( 140, new Int_FieldMT( 1, this, false ));	//  (Ub0)
		varDev.Add( 141, new Int_FieldMT( 1, this, false ));	//  (Uc0)
		varDev.Add( 142, new Int_FieldMT( 1, this, false ));	//  (3I0)
		varDev.Add( 143, new Int_FieldMT( 1, this, false ));	//  (I21, I22)
		varDev.Add( 144, new Int_FieldMT( 1, this, false ));	// c(Максимальное время срабатывания выключателя)
		varDev.Add( 145, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации Ua0)
		varDev.Add( 149, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации Ub0)
		varDev.Add( 153, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации Uc0)
		varDev.Add( 157, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации 3I0)
		varDev.Add( 161, new DateTime4_FieldMT( 4, this, false ));	//  (время регистрации I21, I22)
		varDev.Add( 169, new DateTime4_FieldMT( 4, this, false ));	//  (астрономическое время регистрации max/min значений   )
		varDev.Add( 195, new Real_FieldMT( 2, this, false ));	// В(Uao=)
		varDev.Add( 197, new Real_FieldMT( 2, this, false ));	// В(Ubo=)
		varDev.Add( 199, new Real_FieldMT( 2, this, false ));	// В(Uco=)
		varDev.Add( 201, new Real_FieldMT( 2, this, false ));	// А(I2=)
		varDev.Add( 203, new Real_FieldMT( 2, this, false ));	// В(3Uo=)
		varDev.Add( 205, new Real_FieldMT( 2, this, false ));	// А(I1=)
		varDev.Add( 211, new Real_FieldMT( 2, this, false ));	// B(U2)
		varDev.Add( 215, new Real_FieldMT( 2, this, false ));	// Гц(F=)
		varDev.Add( 10280, new DateTimeUTC_FieldMT( 2, this, false ));	//  (Дата приема по часам ФК)
		varDev.Add( 10282, new Bit_FieldMT( 1, this, false ));	//  (Коды срабатывания защиты)
		varDev.Add( 10284, new Bit_FieldMT( 1, this, false ));	//  (Коды пускавшихся защит)
		varDev.Add( 10285, new Int_FieldMT( 1, this, false ));	// В(Uao=)
		varDev.Add( 10286, new Int_FieldMT( 1, this, false ));	// В(Ubo=)
		varDev.Add( 10287, new Int_FieldMT( 1, this, false ));	// В(Uco=)
		varDev.Add( 10288, new Int_FieldMT( 1, this, false ));	// А(I2=)
		varDev.Add( 10289, new Int_FieldMT( 1, this, false ));	// В(3Uo=)
		varDev.Add( 10290, new Int_FieldMT( 1, this, false ));	// А(I1=)
		varDev.Add( 10293, new Int_FieldMT( 1, this, false ));	// B(U2)
		varDev.Add( 10295, new Int_FieldMT( 1, this, false ));	// Гц(F=)
		varDev.Add( 10297, new Int_FieldMT( 1, this, false ));	// В(Uao=)
		varDev.Add( 10298, new Int_FieldMT( 1, this, false ));	// В(Ubo=)
		varDev.Add( 10299, new Int_FieldMT( 1, this, false ));	// В(Uco=)
		varDev.Add( 10300, new Int_FieldMT( 1, this, false ));	// А(I2=)
		varDev.Add( 10301, new Int_FieldMT( 1, this, false ));	// В(3Uo=)
		varDev.Add( 10302, new Int_FieldMT( 1, this, false ));	// А(I1=)
		varDev.Add( 10305, new Int_FieldMT( 1, this, false ));	// B(U2)
		varDev.Add( 10307, new Int_FieldMT( 1, this, false ));	// Гц(F=)
		varDev.Add( 10309, new UInt_FieldMT( 1, this, false ));	// 1/100c(Выдержка)
		varDev.Add( 10310, new UInt_FieldMT( 1, this, false ));	// 1/100c(Время срабатывания выключателя)
		varDev.Add( 10311, new Bit_FieldMT( 1, this, false ));	//  (Входные дискретные сигналы на момент пуска защит)
		varDev.Add( 10312, new Bit_FieldMT( 1, this, false ));	//  (Входные/выходные дискретные сигналы на момент пуска защит)
		varDev.Add( 10313, new Bit_FieldMT( 1, this, false ));	//  (Входные/выходные дискретные сигналы на момент пуска защит)
		varDev.Add( 10314, new Bit_FieldMT( 1, this, false ));	//  (Изм. входных дискр. сигналов с момента пуска защит до момента их срабатывания)
		varDev.Add( 10315, new Bit_FieldMT( 1, this, false ));	//  (Изм. входных/выходных дискр. сигналов с момента пуска защит до момента их срабатывания)
		varDev.Add( 10316, new Bit_FieldMT( 1, this, false ));	//  (Изм. входных/выходных дискр. сигналов с момента пуска защит до момента их срабатывания)
		varDev.Add( 10376, new Real_FieldMT( 2, this, false ));	// В(Uao=)
		varDev.Add( 10378, new Real_FieldMT( 2, this, false ));	// В(Ubo=)
		varDev.Add( 10380, new Real_FieldMT( 2, this, false ));	// В(Uco=)
		varDev.Add( 10382, new Real_FieldMT( 2, this, false ));	// А(I2=)
		varDev.Add( 10384, new Real_FieldMT( 2, this, false ));	// В(3Uo=)
		varDev.Add( 10386, new Real_FieldMT( 2, this, false ));	// А(I1=)
		varDev.Add( 10392, new Real_FieldMT( 2, this, false ));	// B(U2)
		varDev.Add( 10396, new Real_FieldMT( 2, this, false ));	// Гц(F=)
		varDev.Add( 62000, new DateTimeUTC_FieldMT( 2, this, false ));	//  (дата приема по часам ФК)
		varDev.Add( 62002, new DateTime4_FieldMT( 4, this, false ));	//  (астрономическое время записи уставок)
		varDev.Add( 62006, new BCDPack_FieldMT( 1, this, false ));	// В(3Uo озз >=)
		varDev.Add( 62007, new BCDPack_FieldMT( 1, this, false ));	// В(U2озз=)
		varDev.Add( 62008, new BCDPack_FieldMT( 1, this, false ));	// c(Tозз=)
		varDev.Add( 62009, new BCDPack_FieldMT( 1, this, false ));	// В(Uзмн1<= )
		varDev.Add( 62010, new BCDPack_FieldMT( 1, this, false ));	// c(Tзмн1=)
		varDev.Add( 62011, new BCDPack_FieldMT( 1, this, false ));	// В(U2змн1=)
		varDev.Add( 62012, new BCDPack_FieldMT( 1, this, false ));	// В(Uзмн2<=)
		varDev.Add( 62013, new BCDPack_FieldMT( 1, this, false ));	// c(Tзмн2=)
		varDev.Add( 62014, new BCDPack_FieldMT( 1, this, false ));	// В(U2змн2=)
		varDev.Add( 62015, new BCDPack_FieldMT( 1, this, false ));	// В(U2авр>=)
		varDev.Add( 62016, new BCDPack_FieldMT( 1, this, false ));	// Гц(Fавр<=)
		varDev.Add( 62017, new BCDPack_FieldMT( 1, this, false ));	// В(Uавр<=)
		varDev.Add( 62018, new BCDPack_FieldMT( 1, this, false ));	// c(Tавр=)
		varDev.Add( 62019, new BCDPack_FieldMT( 1, this, false ));	// В(U2равр<=)
		varDev.Add( 62020, new BCDPack_FieldMT( 1, this, false ));	// Гц(Fравр>=)
		varDev.Add( 62021, new BCDPack_FieldMT( 1, this, false ));	// В(Uравр>=)
		varDev.Add( 62022, new BCDPack_FieldMT( 1, this, false ));	// В(3Uo равр>=)
		varDev.Add( 62023, new BCDPack_FieldMT( 1, this, false ));	// В(U2нцн>=)
		varDev.Add( 62024, new BCDPack_FieldMT( 1, this, false ));	// В(Uнцн<=)
		varDev.Add( 62025, new BCDPack_FieldMT( 1, this, false ));	// c(Tнцн=)
		varDev.Add( 62026, new BCDPack_FieldMT( 1, this, false ));	// В(3Uo н.нцн<=)
		varDev.Add( 62027, new BCDPack_FieldMT( 1, this, false ));	// c(Tн.нцн=)
		varDev.Add( 62028, new BCDPack_FieldMT( 1, this, false ));	// c(Тсв мтз=)
		varDev.Add( 62029, new BCDPack_FieldMT( 1, this, false ));	// c(Твв мтз=)
		varDev.Add( 62030, new BCDPack_FieldMT( 1, this, false ));	// c(Тсв озз=)
		varDev.Add( 62031, new BCDPack_FieldMT( 1, this, false ));	// c(Твв озз=)
		varDev.Add( 62032, new BCDPack_FieldMT( 1, this, false ));	// c(РПН Тсраб=)
		varDev.Add( 62033, new BCDPack_FieldMT( 1, this, false ));	// c(РПН Тпер=)
		varDev.Add( 62034, new BCDPack_FieldMT( 1, this, false ));	// шт(РПН кол. отп.=)
		varDev.Add( 62035, new BCDPack_FieldMT( 1, this, false ));	// №(РПН № ср. отп=)
		varDev.Add( 62036, new BCDPack_FieldMT( 1, this, false ));	// c(РПН Трпн=)
		varDev.Add( 62037, new BCDPack_FieldMT( 1, this, false ));	// с(Пр1 Tз=)
		varDev.Add( 62038, new BCDPack_FieldMT( 1, this, false ));	// Ом(Пр1 Rкор=)
		varDev.Add( 62039, new BCDPack_FieldMT( 1, this, false ));	// В(Пр1 Uвзч=)
		varDev.Add( 62040, new BCDPack_FieldMT( 1, this, false ));	// В(Пр1 Uнзч=)
		varDev.Add( 62041, new BCDPack_FieldMT( 1, this, false ));	// c(Пр2 Tз=)
		varDev.Add( 62042, new BCDPack_FieldMT( 1, this, false ));	// Ом(Пр2 Rкор=)
		varDev.Add( 62043, new BCDPack_FieldMT( 1, this, false ));	// В(Пр2 Uвзч=)
		varDev.Add( 62044, new BCDPack_FieldMT( 1, this, false ));	// В(Пр2 Uнзч=)
		varDev.Add( 62045, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62046, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62047, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62048, new Bit_FieldMT( 1, this, false ));	//  (Программные ключи)
		varDev.Add( 62053, new BCD_FieldMT( 1, this, false ));	//  (Числитель коэффищиента трансформации для  токов компенсации  I1, I2)
		varDev.Add( 62054, new BCD_FieldMT( 1, this, false ));	//  (Знаменатель коэффищиента трансформации для фазных токов Ia, Ib, Ic)
		varDev.Add( 62056, new BCD_FieldMT( 1, this, false ));	//  (Коэффициент трансформации тока 3Io)
		varDev.Add( 62100, new DateTimeUTC_FieldMT( 2, this, false ));	//  (дата приема по часам ФК )
		varDev.Add( 62111, new Int_FieldMT( 1, this, false ));	//  (Суммарное количество отключений)
		varDev.Add( 62112, new BCD_FieldMT( 1, this, false ));	//  (ОЗЗ пуск)
		varDev.Add( 62113, new BCD_FieldMT( 1, this, false ));	//  (ОЗЗ сраб)
		varDev.Add( 62114, new BCD_FieldMT( 1, this, false ));	//  (ЗМН1 пуск)
		varDev.Add( 62115, new BCD_FieldMT( 1, this, false ));	//  (ЗМН1 сраб)
		varDev.Add( 62116, new BCD_FieldMT( 1, this, false ));	//  (ЗМН2 пуск)
		varDev.Add( 62117, new BCD_FieldMT( 1, this, false ));	//  (ЗМН2 сраб)
		varDev.Add( 62118, new BCD_FieldMT( 1, this, false ));	//  (НЦН пуск)
		varDev.Add( 62119, new BCD_FieldMT( 1, this, false ));	//  (НЦН сраб)
		varDev.Add( 62120, new BCD_FieldMT( 1, this, false ));	//  (Н.НЦН пуск)
		varDev.Add( 62121, new BCD_FieldMT( 1, this, false ));	//  (Н.НЦН сраб)
		varDev.Add( 62122, new BCD_FieldMT( 1, this, false ));	//  (АВР пуск)
		varDev.Add( 62123, new BCD_FieldMT( 1, this, false ));	//  (АВР сраб)
		varDev.Add( 62124, new BCD_FieldMT( 1, this, false ));	//  (ЛЗШ-МТЗ СВ пуск)
		varDev.Add( 62125, new BCD_FieldMT( 1, this, false ));	//  (ЛЗШ-МТЗ СВ сраб)
		varDev.Add( 62126, new BCD_FieldMT( 1, this, false ));	//  (ЛЗШ-МТЗ ВВ пуск)
		varDev.Add( 62127, new BCD_FieldMT( 1, this, false ));	//  (ЛЗШ-МТЗ ВВ сраб)
		varDev.Add( 62128, new BCD_FieldMT( 1, this, false ));	//  (ЛЗШ-ОЗЗ СВ пуск)
		varDev.Add( 62129, new BCD_FieldMT( 1, this, false ));	//  (ЛЗШ-ОЗЗ СВ сраб)
		varDev.Add( 62130, new BCD_FieldMT( 1, this, false ));	//  (ЛЗШ-ОЗЗ ВВ пуск)
		varDev.Add( 62131, new BCD_FieldMT( 1, this, false ));	//  (ЛЗШ-ОЗЗ ВВ сраб)
		varDev.Add( 62132, new BCD_FieldMT( 1, this, false ));	//  (РПН приб. (сотни))
		varDev.Add( 62133, new BCD_FieldMT( 1, this, false ));	//  (РПН приб. )
		varDev.Add( 62134, new BCD_FieldMT( 1, this, false ));	//  (РПН убав. (сотни))
		varDev.Add( 62135, new BCD_FieldMT( 1, this, false ));	//  (РПН убав.)
		varDev.Add( 62136, new BCD_FieldMT( 1, this, false ));	//  (Текущая отпайка)
		varDev.Add( 62138, new DateTime3_FieldMT( 3, this, false ));	//  (Дата сброса накопительной информации.)
		varDev.Add( 165, new DateTime4_FieldMT( 4, this, false ));	// (Астрономическое время регистрации срабатывания выключателя)
		varDev.Add( 10318, new DateTime4_FieldMT( 4, this, false ));	// (Время аварии)
		varDev.Add( 44, new Bit_FieldMT( 1, this, false ));	// (Программа уставок)
		ConfigureMF(ref varDev, "");
	}
	public override string	ToString()
	{
		return "BMRZ_KN_01_01_11";
	}
	public override void	ConfigureMF(ref Hashtable vD, string modfileName)
	{}
}
}

