using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
namespace NetCrzaDevices
{
/// <summary>
///     classBMRZ_TD_04_30_11
/// </summary>
public class BMRZ_TD_04_30_11 : BMRZ
{
	public BMRZ_TD_04_30_11(int nfc, int ndev, int size_memDev, string devname)
	{
		NFC			= nfc;
		NDev			= ndev;
		DeviceName	= devname;
		varDev		= new Hashtable();
		
		varDev.Add( 25, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 26, new Bit_FieldMT( 1, this, false ));	// (chanel3)
		varDev.Add( 27, new Bit_FieldMT( 1, this, false ));	// (chanel10)
		varDev.Add( 33, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia ВН)
		varDev.Add( 34, new Int_FieldMT( 1, this, false ));	// (chanel1=Ib ВН)
		varDev.Add( 35, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic ВН)
		varDev.Add( 36, new Int_FieldMT( 1, this, false ));	// (chanel3=Ia СН)
		varDev.Add( 37, new Int_FieldMT( 1, this, false ));	// (chanel4=Ib СН)
		varDev.Add( 38, new Int_FieldMT( 1, this, false ));	// (chanel5=Ic СН)
		varDev.Add( 39, new Int_FieldMT( 1, this, false ));	// (chanel6=Ia НН)
		varDev.Add( 40, new Int_FieldMT( 1, this, false ));	// (chanel7=Ib НН)
		varDev.Add( 41, new Int_FieldMT( 1, this, false ));	// (chanel8=Ic НН)
		varDev.Add( 42, new Int_FieldMT( 1, this, false ));	// (chanel9=IdA)
		varDev.Add( 43, new Int_FieldMT( 1, this, false ));	// (chanel10=IdB)
		varDev.Add( 44, new Int_FieldMT( 1, this, false ));	// (chanel11=IdC)
		varDev.Add( 45, new Int_FieldMT( 1, this, false ));	// (chanel12=IтA)
		varDev.Add( 46, new Int_FieldMT( 1, this, false ));	// (chanel13=IтB)
		varDev.Add( 47, new Int_FieldMT( 1, this, false ));	// (chanel14=IтC)
		varDev.Add( 48, new Int_FieldMT( 1, this, false ));	// (chanel15=F)
		varDev.Add( 10282, new Bit_FieldMT( 1, this, false ));	// (byte0_5)
		varDev.Add( 10283, new Bit_FieldMT( 1, this, false ));	// (byte2_0)
		varDev.Add( 10285, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia ВН)
		varDev.Add( 10286, new Int_FieldMT( 1, this, false ));	// (chanel1=Ib ВН)
		varDev.Add( 10287, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic ВН)
		varDev.Add( 10288, new Int_FieldMT( 1, this, false ));	// (chanel3=Ia СН)
		varDev.Add( 10289, new Int_FieldMT( 1, this, false ));	// (chanel4=Ib СН)
		varDev.Add( 10290, new Int_FieldMT( 1, this, false ));	// (chanel5=Ic СН)
		varDev.Add( 10291, new Int_FieldMT( 1, this, false ));	// (chanel6=Ia НН)
		varDev.Add( 10292, new Int_FieldMT( 1, this, false ));	// (chanel7=Ib НН)
		varDev.Add( 10293, new Int_FieldMT( 1, this, false ));	// (chanel8=Ic НН)
		varDev.Add( 10294, new Int_FieldMT( 1, this, false ));	// (chanel9=IdA)
		varDev.Add( 10295, new Int_FieldMT( 1, this, false ));	// (chanel10=IdB)
		varDev.Add( 10296, new Int_FieldMT( 1, this, false ));	// (chanel11=IdC)
		varDev.Add( 10297, new Int_FieldMT( 1, this, false ));	// (chanel12=IтA)
		varDev.Add( 10298, new Int_FieldMT( 1, this, false ));	// (chanel13=IтB)
		varDev.Add( 10299, new Int_FieldMT( 1, this, false ));	// (chanel14=IтC)
		varDev.Add( 10300, new Int_FieldMT( 1, this, false ));	// (chanel15=F)
		varDev.Add( 10302, new Int_FieldMT( 1, this, false ));	// (chanel0=Ia ВН)
		varDev.Add( 10303, new Int_FieldMT( 1, this, false ));	// (chanel1=Ib ВН)
		varDev.Add( 10304, new Int_FieldMT( 1, this, false ));	// (chanel2=Ic ВН)
		varDev.Add( 10305, new Int_FieldMT( 1, this, false ));	// (chanel3=Ia СН)
		varDev.Add( 10306, new Int_FieldMT( 1, this, false ));	// (chanel4=Ib СН)
		varDev.Add( 10307, new Int_FieldMT( 1, this, false ));	// (chanel5=Ic СН)
		varDev.Add( 10308, new Int_FieldMT( 1, this, false ));	// (chanel6=Ia НН)
		varDev.Add( 10309, new Int_FieldMT( 1, this, false ));	// (chanel7=Ib НН)
		varDev.Add( 10310, new Int_FieldMT( 1, this, false ));	// (chanel8=Ic НН)
		varDev.Add( 10311, new Int_FieldMT( 1, this, false ));	// (chanel9=IdA)
		varDev.Add( 10312, new Int_FieldMT( 1, this, false ));	// (chanel10=IdB)
		varDev.Add( 10313, new Int_FieldMT( 1, this, false ));	// (chanel11=IdC)
		varDev.Add( 10314, new Int_FieldMT( 1, this, false ));	// (chanel12=IтA)
		varDev.Add( 10315, new Int_FieldMT( 1, this, false ));	// (chanel13=IтB)
		varDev.Add( 10316, new Int_FieldMT( 1, this, false ));	// (chanel14=IтC)
		varDev.Add( 10317, new Int_FieldMT( 1, this, false ));	// (chanel15=F)
		varDev.Add( 10319, new UInt_FieldMT( 1, this, false ));	// ()
		varDev.Add( 10320, new UInt_FieldMT( 1, this, false ));	// ()
		varDev.Add( 10321, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 10322, new Bit_FieldMT( 1, this, false ));	// (chanel3)
		varDev.Add( 10323, new Bit_FieldMT( 1, this, false ));	// (chanel10)
		varDev.Add( 10324, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 10325, new Bit_FieldMT( 1, this, false ));	// (chanel3)
		varDev.Add( 10326, new Bit_FieldMT( 1, this, false ));	// (chanel10)
		varDev.Add( 10328, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 62006, new BCDPack_FieldMT( 1, this, false ));	// (Ustav0=0,"Iдто)
		varDev.Add( 62007, new BCDPack_FieldMT( 1, this, false ));	// (Ustav1=0,"Iдзт.нач. (без учета РПН))
		varDev.Add( 62008, new BCDPack_FieldMT( 1, this, false ));	// (Ustav2=0,"Кторм.2 (без учета РПН))
		varDev.Add( 62009, new BCDPack_FieldMT( 1, this, false ));	// (Ustav3=0,"Кторм.3 (без учета РПН))
		varDev.Add( 62010, new BCDPack_FieldMT( 1, this, false ));	// (Ustav4=0,"Iдзт.нач. (с учетом РПН))
		varDev.Add( 62011, new BCDPack_FieldMT( 1, this, false ));	// (Ustav5=0,"Кторм.2 (с учетом РПН))
		varDev.Add( 62012, new BCDPack_FieldMT( 1, this, false ));	// (Ustav6=0,"Кторм.3 (с учетом РПН))
		varDev.Add( 62013, new BCDPack_FieldMT( 1, this, false ));	// (Ustav7=0,"Кипб)
		varDev.Add( 62014, new BCDPack_FieldMT( 1, this, false ));	// (Ustav8=0,"Туров)
		varDev.Add( 62015, new BCDPack_FieldMT( 1, this, false ));	// (Ustav9=0,"Тоткл)
		varDev.Add( 62016, new UInt_FieldMT( 1, this, false ));	// (Ustav10=0,"Схема)
		varDev.Add( 62017, new BCDPack_FieldMT( 1, this, false ));	// (Ustav11=0,"Sт.ном)
		varDev.Add( 62018, new BCDPack_FieldMT( 1, this, false ));	// (Ustav12=0,"Uном.ВН)
		varDev.Add( 62019, new BCDPack_FieldMT( 1, this, false ));	// (Ustav13=0,"Uном.НН)
		varDev.Add( 62020, new BCDPack_FieldMT( 1, this, false ));	// (Ustav14=0,"Uном.СН)
		varDev.Add( 62021, new BCDPack_FieldMT( 1, this, false ));	// (Ustav15=0,"Nст. РПН)
		varDev.Add( 62022, new BCDPack_FieldMT( 1, this, false ));	// (Ustav16=0,"Шаг РПН)
		varDev.Add( 62023, new BCDPack_FieldMT( 1, this, false ));	// (Ustav17=0,"Ктт.ВН)
		varDev.Add( 62024, new UInt_FieldMT( 1, this, false ));	// (Ustav18=0,"Ктт.ВН)
		varDev.Add( 62025, new BCDPack_FieldMT( 1, this, false ));	// (Ustav19=0,"Ктт.НН)
		varDev.Add( 62026, new UInt_FieldMT( 1, this, false ));	// (Ustav20=0,"Ктт.НН)
		varDev.Add( 62027, new BCDPack_FieldMT( 1, this, false ));	// (Ustav21=0,"Ктт.СН)
		varDev.Add( 62028, new UInt_FieldMT( 1, this, false ));	// (Ustav22=0,"Ктт.СН)
		varDev.Add( 62029, new UInt_FieldMT( 1, this, false ));	// (Ustav23=0,"Iном ПТН ВН)
		varDev.Add( 62030, new UInt_FieldMT( 1, this, false ));	// (Ustav24=0,"Iном ПТН НН)
		varDev.Add( 62031, new UInt_FieldMT( 1, this, false ));	// (Ustav25=0,"Iном ПТН CH)
		varDev.Add( 62032, new BCDPack_FieldMT( 1, this, false ));	// (Ustav26=0,"Кв.ДТО)
		varDev.Add( 62033, new BCDPack_FieldMT( 1, this, false ));	// (Ustav27=0,"Кв.ДЗТ)
		varDev.Add( 62034, new BCDPack_FieldMT( 1, this, false ));	// (Ustav28=0,"Кпост.)
		varDev.Add( 62035, new BCDPack_FieldMT( 1, this, false ));	// (Ustav29=0,"Кнб.с.)
		varDev.Add( 62036, new BCDPack_FieldMT( 1, this, false ));	// (Ustav30=0,"Iуров)
		varDev.Add( 62037, new Bit_FieldMT( 1, this, false ));	// (Config0_0)
		varDev.Add( 62002, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 62112, new BCD_FieldMT( 1, this, false ));	// (Count0)
		varDev.Add( 62113, new BCD_FieldMT( 1, this, false ));	// (Count1)
		varDev.Add( 62114, new BCD_FieldMT( 1, this, false ));	// (Count2)
		varDev.Add( 62115, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 28, new Bit_FieldMT( 1, this, false ));	// (byte0_0)
		varDev.Add( 0, new BCD_FieldMT( 1, this, false ));	// (Reg_Block_ID)
		varDev.Add( 1, new Stringz_FieldMT( 16, this, false ));	// (Reg_Slave_ID)
		varDev.Add( 17, new BCD_FieldMT( 1, this, false ));	// (Reg_Version)
		varDev.Add( 19, new DateTime4_FieldMT( 4, this, false ));	// (Reg_Time)
		varDev.Add( 23, new UInt_FieldMT( 1, this, false ));	// (Reg_Status_Cnt)
		varDev.Add( 24, new Bit_FieldMT( 1, this, false ));	// (Reg_Status)
		varDev.Add( 30, new Bit_FieldMT( 1, this, false ));	// (Reg_Err)
		varDev.Add( 32, new Bit_FieldMT( 1, this, false ));	// (Reg_Err)
		varDev.Add( 139, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 140, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 141, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 142, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 143, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 144, new Int_FieldMT( 1, this, false ));	// (Reg_Max_Time_BYKL)
		varDev.Add( 145, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign1)
		varDev.Add( 149, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign2)
		varDev.Add( 153, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign3)
		varDev.Add( 157, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign4)
		varDev.Add( 161, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign5)
		varDev.Add( 165, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_BYKL)
		varDev.Add( 169, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_Sbros)
		varDev.Add( 60001, new Bit_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60002, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60003, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60004, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60005, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60006, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60007, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60008, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60009, new DateTimeUTC_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60011, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60012, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60013, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60014, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60015, new Stringz_FieldMT( 17, this, false ));	// (null)
		varDev.Add( 60050, new UDInt_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60052, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60053, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60054, new DateTimeUTC_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60056, new Int_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60057, new Int_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60058, new Stringz_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60060, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60061, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 195, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 197, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 199, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 201, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 203, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 205, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 207, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 209, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 211, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 213, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 215, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 217, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 219, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 221, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 223, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 225, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 227, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 229, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10376, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10378, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10380, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10382, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10384, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10386, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10388, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10390, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10392, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10394, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10396, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10398, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10400, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10402, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10404, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10406, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10408, new Real_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 10410, new Real_FieldMT( 2, this, false ));	// (null)
		ConfigureMF(ref varDev, "");
	}
	public override string	ToString()
	{
		return "BMRZ_TD_04_30_11";
	}
	public override void	ConfigureMF(ref Hashtable vD, string modfileName)
	{}
}
}

