using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
namespace NetCrzaDevices
{
/// <summary>
///     classUSO_MT_A_02
/// </summary>
public class USO_MT_A_02 : BMRZ
{
	public USO_MT_A_02(int nfc, int ndev, int size_memDev, string devname)
	{
		NFC			= nfc;
		NDev			= ndev;
		DeviceName	= devname;
		varDev		= new Hashtable();
		
		varDev.Add( 25, new Bit_FieldMT( 1, this, false ));	// (chanel0)
		varDev.Add( 26, new Bit_FieldMT( 1, this, false ));	// (chanel16)
		varDev.Add( 31, new Bit_FieldMT( 1, this, false ));	// (chanel7)
		varDev.Add( 33, new Int_FieldMT( 1, this, false ));	// (chanel0=Ua1)
		varDev.Add( 34, new Int_FieldMT( 1, this, false ));	// (chanel1=Ub1)
		varDev.Add( 35, new Int_FieldMT( 1, this, false ));	// (chanel2=Uc1)
		varDev.Add( 36, new Int_FieldMT( 1, this, false ));	// (chanel3=Ua2)
		varDev.Add( 37, new Int_FieldMT( 1, this, false ));	// (chanel4=Ub2)
		varDev.Add( 38, new Int_FieldMT( 1, this, false ));	// (chanel5=Uc2)
		varDev.Add( 45, new Int_FieldMT( 1, this, false ));	// (chanel12)
		varDev.Add( 46, new Int_FieldMT( 1, this, false ));	// (chanel13)
		varDev.Add( 47, new Int_FieldMT( 1, this, false ));	// (chanel14)
		varDev.Add( 48, new Int_FieldMT( 1, this, false ));	// (chanel15)
		varDev.Add( 49, new Int_FieldMT( 1, this, false ));	// (chanel16)
		varDev.Add( 50, new Int_FieldMT( 1, this, false ));	// (chanel17)
		varDev.Add( 0, new BCD_FieldMT( 1, this, false ));	// (Reg_Block_ID)
		varDev.Add( 1, new Stringz_FieldMT( 16, this, false ));	// (Reg_Slave_ID)
		varDev.Add( 17, new BCD_FieldMT( 1, this, false ));	// (Reg_Version)
		varDev.Add( 19, new DateTime4_FieldMT( 4, this, false ));	// (Reg_Time)
		varDev.Add( 24, new Bit_FieldMT( 1, this, false ));	// (Reg_Status)
		varDev.Add( 30, new Bit_FieldMT( 1, this, false ));	// (Reg_Err)
		varDev.Add( 32, new Bit_FieldMT( 1, this, false ));	// (Reg_Err)
		varDev.Add( 139, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 140, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 141, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 142, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 143, new Int_FieldMT( 1, this, false ));	// (Reg_MaxMin_Asign)
		varDev.Add( 144, new Int_FieldMT( 1, this, false ));	// (Reg_Max_Time_BYKL)
		varDev.Add( 145, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign1)
		varDev.Add( 149, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign2)
		varDev.Add( 153, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign3)
		varDev.Add( 157, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign4)
		varDev.Add( 161, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_ Asign5)
		varDev.Add( 165, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_BYKL)
		varDev.Add( 169, new DateTime4_FieldMT( 4, this, false ));	// (Reg_DateTime_Sbros)
		varDev.Add( 60001, new Bit_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60002, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60003, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60004, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60005, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60006, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60007, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60008, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60009, new DateTimeUTC_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60011, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60012, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60013, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60014, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60015, new Stringz_FieldMT( 17, this, false ));	// (null)
		varDev.Add( 60050, new UDInt_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60052, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60053, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60054, new DateTimeUTC_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60056, new Int_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60057, new Int_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60058, new Stringz_FieldMT( 2, this, false ));	// (null)
		varDev.Add( 60060, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 60061, new UInt_FieldMT( 1, this, false ));	// (null)
		varDev.Add( 62006, new UInt_FieldMT( 1, this, false ));	// (Ustav0=2,Количество осц)
		varDev.Add( 62007, new UInt_FieldMT( 1, this, false ));	// (Ustav1=2,Частота дискретизации)
		varDev.Add( 62016, new BCDPack_FieldMT( 1, this, false ));	// (Ustav10=2,Tua1=)
		varDev.Add( 62017, new BCDPack_FieldMT( 1, this, false ));	// (Ustav11=2,Tub1=)
		varDev.Add( 62018, new BCDPack_FieldMT( 1, this, false ));	// (Ustav12=2,Tuc1=)
		varDev.Add( 62019, new BCDPack_FieldMT( 1, this, false ));	// (Ustav13=2,Tua2=)
		varDev.Add( 62020, new BCDPack_FieldMT( 1, this, false ));	// (Ustav14=2,Tub2=)
		varDev.Add( 62021, new BCDPack_FieldMT( 1, this, false ));	// (Ustav15=2,Tuc2=)
		varDev.Add( 62024, new UInt_FieldMT( 1, this, false ));	// (Ustav18=2,Скорость 485=)
		varDev.Add( 62025, new BCDPack_FieldMT( 1, this, false ));	// (Ustav19=2,Адрес 485=)
		varDev.Add( 62008, new BCDPack_FieldMT( 1, this, false ));	// (Ustav2=2,Ua1=)
		varDev.Add( 62026, new BCDPack_FieldMT( 1, this, false ));	// (Ustav20=2,Предистория=)
		varDev.Add( 62027, new BCDPack_FieldMT( 1, this, false ));	// (Ustav21=2,Твоз Двых1=)
		varDev.Add( 62028, new BCDPack_FieldMT( 1, this, false ));	// (Ustav22=2,Твоз Двых2=)
		varDev.Add( 62029, new BCDPack_FieldMT( 1, this, false ));	// (Ustav23=2,Твоз Двых3=)
		varDev.Add( 62030, new BCDPack_FieldMT( 1, this, false ));	// (Ustav24=2,Твоз Двых4=)
		varDev.Add( 62031, new BCDPack_FieldMT( 1, this, false ));	// (Ustav25=2,Твоз Двых5=)
		varDev.Add( 62032, new BCDPack_FieldMT( 1, this, false ));	// (Ustav26=2,Твоз Двых6=)
		varDev.Add( 62033, new BCDPack_FieldMT( 1, this, false ));	// (Ustav27=2,Твоз Двых7=)
		varDev.Add( 62034, new BCDPack_FieldMT( 1, this, false ));	// (Ustav28=2,Твоз Двых8=)
		varDev.Add( 62035, new BCDPack_FieldMT( 1, this, false ));	// (Ustav29=2,Твоз Двых9=)
		varDev.Add( 62009, new BCDPack_FieldMT( 1, this, false ));	// (Ustav3=2,Ub1=)
		varDev.Add( 62036, new BCDPack_FieldMT( 1, this, false ));	// (Ustav30=2,Твоз Двых10=)
		varDev.Add( 62037, new BCDPack_FieldMT( 1, this, false ));	// (Ustav31=2,Твоз Двых11=)
		varDev.Add( 62038, new BCDPack_FieldMT( 1, this, false ));	// (Ustav32=2,Твоз Двых12=)
		varDev.Add( 62039, new BCDPack_FieldMT( 1, this, false ));	// (Ustav33=2,Твоз Двых15=)
		varDev.Add( 62040, new BCDPack_FieldMT( 1, this, false ));	// (Ustav34=2,Твоз Двых16=)
		varDev.Add( 62041, new BCDPack_FieldMT( 1, this, false ));	// (Ustav35=2,Тсброса=)
		varDev.Add( 62010, new BCDPack_FieldMT( 1, this, false ));	// (Ustav4=2,Uc1=)
		varDev.Add( 62011, new BCDPack_FieldMT( 1, this, false ));	// (Ustav5=2,Ua2=)
		varDev.Add( 62012, new BCDPack_FieldMT( 1, this, false ));	// (Ustav6=2,Ub2=)
		varDev.Add( 62013, new BCDPack_FieldMT( 1, this, false ));	// (Ustav7=2,Uc2=)
		varDev.Add( 62042, new Bit_FieldMT( 1, this, false ));	// (byte0_0)
		varDev.Add( 62043, new Bit_FieldMT( 1, this, false ));	// (byte2_0)
		varDev.Add( 62044, new Bit_FieldMT( 1, this, false ));	// (byte4_0)
		varDev.Add( 62045, new Bit_FieldMT( 1, this, false ));	// (byte6_0)
		varDev.Add( 62046, new Bit_FieldMT( 1, this, false ));	// (byte0_0)
		varDev.Add( 62047, new Bit_FieldMT( 1, this, false ));	// (byte2_0)
		varDev.Add( 62048, new Bit_FieldMT( 1, this, false ));	// (byte4_0)
		varDev.Add( 62049, new Bit_FieldMT( 1, this, false ));	// (byte6_0)
		varDev.Add( 62002, new DateTime4_FieldMT( 4, this, false ));	// ()
		varDev.Add( 195, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 197, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 199, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 201, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 203, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 205, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 219, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 221, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 223, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 225, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 227, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		varDev.Add( 229, new Real_FieldMT( 2, this, false ));	// А(Ia=)
		ConfigureMF(ref varDev, "");
	}
	public override string	ToString()
	{
		return "USO_MT_A_02";
	}
	public override void	ConfigureMF(ref Hashtable vD, string modfileName)
	{}
}
}

