//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI_MT.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 192, 128")]
        public global::System.Drawing.Color color_btnChAvarCC_pnlColors_pnl2 {
            get {
                return ((global::System.Drawing.Color)(this["color_btnChAvarCC_pnlColors_pnl2"]));
            }
            set {
                this["color_btnChAvarCC_pnlColors_pnl2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 192")]
        public global::System.Drawing.Color color_btnChWarnCC_pnlColors_pnl2 {
            get {
                return ((global::System.Drawing.Color)(this["color_btnChWarnCC_pnlColors_pnl2"]));
            }
            set {
                this["color_btnChWarnCC_pnlColors_pnl2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 192")]
        public global::System.Drawing.Color color_btnChInfoCC_pnlColors_pnl2 {
            get {
                return ((global::System.Drawing.Color)(this["color_btnChInfoCC_pnlColors_pnl2"]));
            }
            set {
                this["color_btnChInfoCC_pnlColors_pnl2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isReqPass {
            get {
                return ((bool)(this["isReqPass"]));
            }
            set {
                this["isReqPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathToLogFile {
            get {
                return ((string)(this["PathToLogFile"]));
            }
            set {
                this["PathToLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500000")]
        public int LogFileMaxSize {
            get {
                return ((int)(this["LogFileMaxSize"]));
            }
            set {
                this["LogFileMaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сохранить")]
        public string WhatToDoLogFileMaxSize {
            get {
                return ((string)(this["WhatToDoLogFileMaxSize"]));
            }
            set {
                this["WhatToDoLogFileMaxSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int NumStringsInMesPanel {
            get {
                return ((int)(this["NumStringsInMesPanel"]));
            }
            set {
                this["NumStringsInMesPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alarm4.wav")]
        public string PathToSoundAvar {
            get {
                return ((string)(this["PathToSoundAvar"]));
            }
            set {
                this["PathToSoundAvar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("alarm2.wav")]
        public string PathToSoundWarn {
            get {
                return ((string)(this["PathToSoundWarn"]));
            }
            set {
                this["PathToSoundWarn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsToolTipShow {
            get {
                return ((bool)(this["IsToolTipShow"]));
            }
            set {
                this["IsToolTipShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowTabForms {
            get {
                return ((bool)(this["IsShowTabForms"]));
            }
            set {
                this["IsShowTabForms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsToolTipRefDesign {
            get {
                return ((bool)(this["IsToolTipRefDesign"]));
            }
            set {
                this["IsToolTipRefDesign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string Precision {
            get {
                return ((string)(this["Precision"]));
            }
            set {
                this["Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600000")]
        public long AliveInterval {
            get {
                return ((long)(this["AliveInterval"]));
            }
            set {
                this["AliveInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogOnlyDisk {
            get {
                return ((bool)(this["LogOnlyDisk"]));
            }
            set {
                this["LogOnlyDisk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTCPServer {
            get {
                return ((bool)(this["IsTCPServer"]));
            }
            set {
                this["IsTCPServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTCPClient {
            get {
                return ((bool)(this["IsTCPClient"]));
            }
            set {
                this["IsTCPClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int IntervalDataReNew {
            get {
                return ((int)(this["IntervalDataReNew"]));
            }
            set {
                this["IntervalDataReNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.1")]
        public string IPPointForSerializeMesPan {
            get {
                return ((string)(this["IPPointForSerializeMesPan"]));
            }
            set {
                this["IPPointForSerializeMesPan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9059")]
        public uint PortPointForSerializeMesPan {
            get {
                return ((uint)(this["PortPointForSerializeMesPan"]));
            }
            set {
                this["PortPointForSerializeMesPan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUDPSecondClient {
            get {
                return ((bool)(this["IsUDPSecondClient"]));
            }
            set {
                this["IsUDPSecondClient"] = value;
            }
        }
    }
}
