//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI_MT {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Hmi_MT : global::System.Configuration.ApplicationSettingsBase {
        
        private static Hmi_MT defaultInstance = ((Hmi_MT)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Hmi_MT())));
        
        public static Hmi_MT Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\\r\n")]
        public string strLogFilename {
            get {
                return ((string)(this["strLogFilename"]));
            }
        }
    }
}
